### ISSUE TITLE
"x in deque" slow

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#1327]
In Heptapod by @arigo on Nov 16, 2012, 17:18

**From (bugs.pypy.org)**

 *Attachments:* [deque_in_bench.py](https://pypy-attachments.s3.amazonaws.com/736937129/e89f38a81694641de848b644a45afc7ecf602a85915bb844f3762288d96ae6cd/deque_in_bench.py)

**Comment by wimglenn** [comment]
Anyone have the correct revision with the fix? The [7a0d27055cb4](https://github.com/pypy/pypy/commit/7a0d27055cb4) mentioned above doesn't seem to exist.  😕

**Comment by cfbolz** [comment]
it's a mercurial hash, not a git hash, I bet
