### ISSUE TITLE
type(None).__repr__(None) gives type error

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#2083]
In Heptapod by bitbucket_importer on Jul 17, 2015, 09:18

*Created originally on Bitbucket by [david_maciver_ (David MacIver)](https://bitbucket.org/[7.3.7](https://github.com/gitlab-importer/pypy/milestone/7)Bb847790a-6381-484a-b7fb-02218c52f3f2%7D/)*

This should return "None" and does on CPython 2.7.10, but on pypy it instead gives a TypeError:

```
>>>> type(None).__repr__(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __repr__() takes exactly 1 argument (2 given)
```

**Comment by mattip** [comment]
Closing, the example now works.
