### ISSUE TITLE
Different behavior of bytes.decode('utf8', 'custom_replace')

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#2389]
In Heptapod by bitbucket_importer on Sep 1, 2016, 10:01

*Created originally on Bitbucket by [kostialopuhin (Konstantin Lopukhin)](https://bitbucket.org/[7.3.7](https://github.com/gitlab-importer/pypy/milestone/7)Bfb5fb8d6-dae1-45a4-8286-947e3578011e%7D/)*

The following program:
```
import codecs

codecs.register_error('custom_replace', lambda exc: (u'\ufffd', exc.start+1))

s1 = b"WORD\xe3\xab"
print(repr(s1.decode('utf8', 'custom_replace')))
print(repr(s1.decode('utf8', 'replace')))

s2 = b"\xef\xbb\xbfWORD\xe3\xabWORD2"
print(repr(s2.decode('utf8', 'custom_replace')))
print(repr(s2.decode('utf8', 'replace')))
```
produces different results on CPython 2.7 (I tried 2.7.6 and 2.7.12) and on PyPy 5.4.0:

```
$ pypy test.py 
u'WORD\ufffd'
u'WORD\ufffd'
u'\ufeffWORD\ufffd\ufffdWORD2'
u'\ufeffWORD\ufffdWORD2'
$ python test.py 
u'WORD\ufffd\ufffd'
u'WORD\ufffd'
u'\ufeffWORD\ufffd\ufffdWORD2'
u'\ufeffWORD\ufffdWORD2'
```

And I think CPython is more consistent here: with a custom replace function, it replaces each invalid byte with given symbol, but PyPy in some cases does a different thing.

The context: this code is used in w3lib here https://github.com/scrapy/w3lib/blob/v1.14.2/w3lib/encoding.py#L176 (the CPython bug reference might be slightly misleading here) to emulate browser behavior for invalid utf8 handling, and CPython with custom_replace agrees with browser behavior here.

**Comment by devdanzin** [comment]
Seems to be fixed:

```python
Python 3.10.14 (75b3de9d9035, Apr 21 2024, 13:13:38)
[PyPy 7.3.16 with MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>> import codecs
>>>> codecs.register_error('custom_replace', lambda exc: (u'\ufffd', exc.start+1))
>>>> b"WORD\xe3\xab".decode('utf8', 'custom_replace')
'WORD´┐¢´┐¢'
```

**Comment by mattip** [comment]
Will close, please open a new issue if you come across this problem again.
