### ISSUE TITLE
multiprocessing.queues.SimpleQueue missing close()

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#2609]
In Heptapod by @arigo on Jul 19, 2017, 09:49

``multiprocessing.queues.SimpleQueue`` should have a close() method.  This is needed to explicitly release the two file descriptors of the Pipe used internally.  I think the following would do:

```
#!diff

diff -r 0b72fd1a7641 lib-python/2.7/multiprocessing/queues.py
--- a/lib-python/2.7/multiprocessing/queues.py  Sun Jul 16 13:41:28 2017 +0200
+++ b/lib-python/2.7/multiprocessing/queues.py  Wed Jul 19 10:45:03 2017 +0200
@@ -358,6 +358,11 @@
             self._wlock = Lock()
         self._make_methods()
 
+    def close(self):
+        # PyPy extension: CPython doesn't have this method!
+        self._reader.close()
+        self._writer.close()
+
     def empty(self):
         return not self._reader.poll()
```

We need to decide if it's ok to add this method when CPython doesn't have it.

**Comment by devdanzin** [comment]
The `close` method was added to Python 3.9 and is present in PyPy 3.9.19. It's still missing in PyPy 2.7.18.

**Comment by mattip** [comment]
We should close this then. We won't backport multiprocessing changes to 2.7.
