### ISSUE TITLE
Add missing crypto algorithms, introduced in cpython3.6

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#2692]
In Heptapod by bitbucket_importer on Oct 30, 2017, 15:35

*Created originally on Bitbucket by [thisch (Thomas Hisch)](https://bitbucket.org/[7.3.7](https://github.com/gitlab-importer/pypy/milestone/7)Ba44403fa-ac20-415b-90fe-1aaebdd3f396%7D/)*

PyPy(3.6) does not yet contain an implementation for the crypto libraries, introduced in cpython3.6 (see https://bugs.python.org/issue16113)

**Comment by mattip** [comment]
Closing, these were implemented at some point.
