### ISSUE TITLE
windows: UnicodeDecodeError when __pycache__ is present

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#2753]
In Heptapod by bitbucket_importer on Feb 13, 2018, 12:32

*Created originally on Bitbucket by [leminaw (leminaw@gmail.com)](https://bitbucket.org/[7.3.7](https://github.com/gitlab-importer/pypy/milestone/7)B3e457b09-62fd-4196-9411-8cd923b5f29e%7D/)*

When the `__pycache__` folder is present, any module I try to import from the current folder raises an `UnicodeDecodeError`.

```
File ".\bifurcations.py", line 4, in <module>
    from utils import replace_patterns, lin_interp
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 12: invalid continuation 
```
In this exemple, if I remove `utils.pypy3-510.pyc` bytescode file from the `__pycache__`, everything runs smoothly.

This problem does not occurs when using CPython.

I currently run pypy on Windows 10, with the folder containing pypy3 in my `PATH` env var, so i do
`pypy3 .\bifurcations.py`

I'm not sure of what file or information join to this. Am I doing anything wrong?

 *Attachments:* [utils.py](https://pypy-attachments.s3.amazonaws.com/736937129/445eb37e8181f10cbc3ecc71a54b32bc6f97a0969844458a20e019629f603ab9/utils.py)

**Comment by mattip** [comment]
Still failing even after the unicode/utf8 rework over the past week.

**Comment by mattip** [comment]
The reproducer now passes.
