### ISSUE TITLE
GNU/Hurd port

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#2848]
In Heptapod by bitbucket_importer on Jun 15, 2018, 22:43

*Created originally on Bitbucket by [sthibaul (Samuel Thibault)](https://bitbucket.org/[7.3.7](https://github.com/gitlab-importer/pypy/milestone/7)B6f2cce61-2845-4775-b558-8a80d4d96bb4%7D/)*

Hello,

I'm trying to port pypy to GNU/Hurd, I have used the attached patch and gotten the build to proceed, but ended up with this:

(text from log.txt)

which, I have to say, I don't understand :)

Samuel

 *Attachments:* [hurd](https://pypy-attachments.s3.amazonaws.com/736937129/82f73dae959ca23565055ca5d77d7ef1e8e5cf8ef28623c0eb5a9d90bd8424dc/hurd)[log.txt](https://pypy-attachments.s3.amazonaws.com/736937129/3116f00312f88c5dbdfe6f87201a4924acff2aa295b5d49815ffc71e8422f1e8/log.txt)[rtyper2.txt](https://pypy-attachments.s3.amazonaws.com/736937129/6fe5bce5f166c21da359e55f501d62262163397568d4f7a0f4ad1904b1c1d2db/rtyper2.txt)[rlib2.txt](https://pypy-attachments.s3.amazonaws.com/736937129/391daf883498595297c8d453b45c872800212abc1197a07af09957fbc2834555/rlib2.txt)[log2.txt](https://pypy-attachments.s3.amazonaws.com/736937129/2ccd136b67e2df2d024b3001b65a477bb286e0aa1e1d04f31a761baa49d35194/log2.txt)[log3.txt](https://pypy-attachments.s3.amazonaws.com/736937129/022dfdd0cda219e69a793842a133b1fa6ea180752894866215b29669a72dea24/log3.txt)[log4.txt](https://pypy-attachments.s3.amazonaws.com/736937129/bd56e07b18f9c0de7a3cbc1daf29667377923cce31b428ef7620db488c79b242/log4.txt)

**Comment by mattip** [comment]
Closing. If someone wants PyPy GNU/Hurd support please open a new issue with the current HEAD of PyPy and newer GNU/Hurd
