### ISSUE TITLE
Pasting into MacOS shell doesn't indent correctly

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#2880]
In Heptapod by bitbucket_importer on Aug 31, 2018, 18:30

*Created originally on Bitbucket by [bramcohen (Bram Cohen)](https://bitbucket.org/[7.3.7](https://github.com/gitlab-importer/pypy/milestone/7)Bd1da817e-1d22-4a15-a5db-0ea445053271%7D/)*

The auto-indent in the MacOS shell, while it's the correct behavior for interactive entering of code, is broken for cut and paste. What happens when you try to paste in a whole function is that the auto-indent for later lines kicks in, then the indentation getting pasted gets added as well, resulting in a syntax error.

The appropriate solution is to make auto-indent not happen in the middle of pastes.

**Comment by mattip** [comment]
Works on latest py3.10 HEAD. Closing.
