### ISSUE TITLE
os functions return '??' for unicode characters in paths on windows

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#2937]
In Heptapod by bitbucket_importer on Jan 6, 2019, 10:32

*Created originally on Bitbucket by [TheElementalOfCreation (Creation Elemental)](https://bitbucket.org/[7.3.7](https://github.com/gitlab-importer/pypy/milestone/7)B92f1135a-406a-4393-b170-4c5f9bfe61a7%7D/)*

I have a few files that contain emojis in their names, and also a folder that has such. Commands like `os.getcwd`, `os.listdir`, `os.path.realpath`, etc. will cause this to happen. This is also a problem with pure windows installations of python2. ( https://bugs.python.org/issue35670?@ok_message=msg%20333100%20created%0Aissue%2035670%20created&@template=item )

I have not yet been able to test if this happens on non-windows installations of pypy2.

For example, say you have a folder simply called '🔭'. If you run python inside of it and run `os.getcwd()` you will simply get `'??'` as the result. This breaks MANY of my programs that depend on knowing exactly where they are, and knowing the contents of a directory to pass to other functions.

**Comment by mattip** [comment]
PyPy no longer crashes nor prints `?` for me, it now can run properly from a unicode-named directory. The console printing is still messed up unless using `chcp 65001`, it now shows random unicode characters instead of `?`.

**Comment by mattip** [comment]
Closing, this is fixed on py3.11 HEAD
