### ISSUE TITLE
Allow downloading the latest build using `latest` as version number.

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#2940]
In Heptapod by bitbucket_importer on Jan 19, 2019, 15:45

*Created originally on Bitbucket by [KOLANICH](https://bitbucket.org/[7.3.7](https://github.com/gitlab-importer/pypy/milestone/7)B6071835d-d262-4e12-8e64-ab871539afd9%7D/)*

Both in BitBucket downloads and buildbot.

**Comment by devdanzin** [comment]
Since there are no more BitBucket downloads and there are permanent links to the latest version in buildbot, I think this can be closed.
