### ISSUE TITLE
PyPy2.7v7.3.0 json UnicodeEncodeError bug

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#3180]
In Heptapod by @xing on Mar 3, 2020, 06:13

I found a bug(pypy2.7v7.3.0):
zipxing@zipdeMacBook-Pro Downloads % more bug.py

`import os
import sys
import json
datas = json.loads('{"key":"\u94bb\u77f3x10000"}')
pyexe = os.path.split(sys.executable)[-1]
bufenv = os.environ.get('PYTHONUNBUFFERED')
print pyexe, 'PYTHONBUFFERED='+str(bufenv), datas["key"]`

zipxing@zipdeMacBook-Pro Downloads % more bug.sh

`export PYTHONUNBUFFERED=
python bug.py
pypy bug.py
export PYTHONUNBUFFERED=1
python bug.py
pypy bug.py`

zipxing@zipdeMacBook-Pro Downloads % ./bug.sh

`Python PYTHONBUFFERED= 钻石x10000
pypy PYTHONBUFFERED= 钻石x10000
Python PYTHONBUFFERED=1 钻石x10000
pypy PYTHONBUFFERED=1 Traceback (most recent call last):
  File "bug.py", line 7, in <module>
    print pyexe, 'PYTHONBUFFERED='+str(bufenv), datas["key"]
UnicodeEncodeError: 'ascii' codec can't encode character u'\u94bb' in position 0: ordinal not in range(128)`

[bug.py](https://pypy-attachments.s3.amazonaws.com/736937129/67c6260161381af5468b1374d67b630bea52b708701fd311aa8d1c5733b3d695/bug.py)

[bug.sh](https://pypy-attachments.s3.amazonaws.com/736937129/f1c85497c331422d13f7742bba74a1adb5c12fbed505abb7f8208f21b9bc78e6/bug.sh)

**Comment by mattip** [comment]
Closing, duplicate of 3178 which was fixed.
