### ISSUE TITLE
Links to the pypy source from within the docs do not work.

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#3216]
In Heptapod by @bostikforever on Apr 27, 2020, 23:01

For instance, see the contributing page: https://doc.pypy.org/en/latest/contributing.html
Links like [pypy/interpreter/module.py](https://foss.heptapod.net/pypy/pypy/src/default/pypy/interpreter/module.py) (which is how it is in the docs page) should instead point to [pypy/interpreter/module.py](https://foss.heptapod.net/pypy/pypy/blob/branch/default/pypy/interpreter/module.py)

This seems to be a rather consistent defect across the docs. Perhaps it is a fallout from the migration from bitbucket to heptapod?

**Comment by AlbertMietus** [comment]
_Just as an update:_ 
The **current docs** (eg https://doc.pypy.org/en/latest/parser.html) still refer to the (**old**)  _foss.heptapod.net_ sources (https://foss.heptapod.net/pypy/pypy/-/blob/branch/default/pypy/interpreter/pyparser/metaparser.py). 

Even although  there is  "edit on GitHub banner :-) 

Hope we can fix this soon

**Comment by mattip** [comment]
Right, this comes from here https://github.com/pypy/pypy/blob/d102094b863ce49b7af030dcb0cecaac515d97c6/pypy/doc/conf.py#L257

Fixing.

**Comment by mattip** [comment]
Fixed in 0cabcb92fefa4b8ac41574a61b46e526fc5cb447, thanks for pointing it out.
