### ISSUE TITLE
hashlib: update() raises TypeError when given memoryview (e.g. BytesIO)

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#3217]
In Heptapod by @mgorny on Apr 30, 2020, 10:32

This is causing problems with [csv23](https://github.com/xflr6/csv23) package.

Trivial reproducer:
```
import hashlib
import io

hashlib.new('sha512').update(io.BytesIO().getbuffer())
```

Exception:
```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    hashlib.new('sha512').update(io.BytesIO().getbuffer())
  File "/usr/lib/pypy3.6/lib_pypy/_hashlib/__init__.py", line 59, in update
    buf = ffi.from_buffer(string)
TypeError: from_buffer() got a 'memoryview' object, which supports the buffer interface but cannot be rendered as a plain raw address on PyPy
```

**Comment by mattip** [comment]
Closing, this now works. Please reopen or open a new issue if there is more to do here. I will note the cvs23 project has [pypy3.9 and pypy3.10 testing](https://github.com/xflr6/csv23/blob/18632cfab4444a39ab22316e57bf8f34b751ff24/.github/workflows/build.yaml#L26).
