### ISSUE TITLE
Implement 3.7 feature signal.set_wakeup_fd(warn_on_full_buffer=False)

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#3227]
In Heptapod by @catern on May 9, 2020, 22:23

The flag warn_on_full_buffer flag to set_wakeup_fd was added in Python 3.7:

https://docs.python.org/3/library/signal.html#signal.set_wakeup_fd

The main user I know of right now is trio: https://github.com/python-trio/trio/issues/109

**Comment by mattip** [comment]
The kwarg has been implemented for a while now. Closing.
