### ISSUE TITLE
PyPy Windows 32 bit converts symlinks to copies of files when doing setup.py bdist_wheel

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#3325]
In Heptapod by @hameerabbasi on Oct 10, 2020, 07:02

Hello. PyPy 32bit Windows (and no other version) converts symlinks to copies of files when doing `setup.py bdist_wheel`.

This leads to issues with my version management system `versioneer` which produces a dirty wheel. Please see [this issue](https://github.com/joerick/cibuildwheel/issues/437) for more details.

**Comment by mattip** [comment]
Closing. We do not support 32bit windows anymore and the symlink support for win64 was added.
