### ISSUE TITLE
windows cffi embedded tests are failing

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#3338]
In Heptapod by @mattip on Nov 4, 2020, 15:25

Some of the `extra_tests/cffi/embedded/test_basic.py` tests are failing on windows on default. When I run the `exe` generated by the `test_first_calls_in_parallel` test under a debugger, it show that `_RPy_ThreadLocals_Get` returns `NULL` in this function
```
static INLINE long _rpygil_get_my_ident(void)
{
#ifdef RPY_TLOFS_thread_ident
    struct pypy_threadlocal_s *p = (struct pypy_threadlocal_s *)_RPy_ThreadLocals_Get();
    assert(p->thread_ident != 0);
    return p->thread_ident;
#else
    // made-up thread identifier
    return 1234;
#endif
```

I think the problem is due to something in the way the `rpython/translator/c/src/thread.local.c` code is using thread local storage in libpypy-c.dll. The code is almost but not quite equivalent to the [example code from MSVC](https://docs.microsoft.com/en-us/windows/win32/dlls/using-thread-local-storage-in-a-dynamic-link-library). This may be connected to some other issues in threading and windows.

**Comment by mattip** [comment]
Closing. The code was refactored and the crashes are gone.
