### ISSUE TITLE
PyType_IsSubtype seems wrong

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#3421]
In Heptapod by @rlamy on Mar 18, 2021, 17:36

According to [the CPython docs](https://docs.python.org/3/c-api/type.html#c.PyType_IsSubtype), `PyType_IsSubtype` ignores the subclassing protocol hooks like `__subclasscheck__()`. Our version seems to implement the full app-level `issubclass()` logic.

**Comment by mattip** [comment]
Closing, we haven't found a failing test for this yet. Please reopen if one exists.
