### ISSUE TITLE
Missing C-API functions  PyState_FindModule

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#3438]
In Heptapod by @mattip on Apr 15, 2021, 10:54

recordclass, a replacement for named tuples, uses the following unimplemented C-API functions: ~~`_PyObject_GetBuiltin` (part of the limited API)~~, `PyState_FindModule`. 

~~Also missing: `PyState_AddModule`, `PyState_RemoveModule`.~~

Edit: `_PyObject_GetBuiltin` is not part of the limited API, maybe I meant `PyEval_GetBuiltins`?

**Comment by mattip** [comment]
Closing. `PyState_FindModule` was implemented in py3.9
