### ISSUE TITLE
LIBDIR has changed on PyPy 7.3.4

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#3442]
In Heptapod by @davidhewitt on Apr 18, 2021, 08:03

On PyPy 7.3.3, the `sysconfig` var `LIBDIR` used to point to the `bin` subdirectory:

```
>>>> import sysconfig
>>>> sysconfig.get_config_var("LIBDIR")
'/home/david/pypy3.7-v7.3.3-linux64/bin'
```

This has changed to the `lib` subdirectory in 7.3.4:

```
>>>> import sysconfig
>>>> sysconfig.get_config_var("LIBDIR")
'/home/david/pypy3.7-v7.3.4-linux64/lib'
```

This change wasn't documented in the [release notes](https://doc.pypy.org/en/latest/release-v7.3.4.html#changelog). I do agree the latter seems more correct. Looks like this commit was the cause: https://foss.heptapod.net/pypy/pypy/-/commit/77bb90aa67ec2b76748c9b96992fc3c3c4bf3fb5

The problem is that `libpypy3-c.so` is still located in the `bin` subdirectory. [PyO3](https://github.com/pyo3/pyo3) was using `LIBDIR` to locate `libpypy3-c.so`, so now with the new PyPy release it can't find it.

I'm happy to be told that PyO3 was doing the wrong thing here (it may need to hard-code the `bin` subdirectory as the library search path?). However this seemed like unintentional breakage so I wanted to flag here.

**Comment by mattip** [comment]
Closing, the problem with LIBDIR was solved.
