### ISSUE TITLE
Missing os.readlink on windows

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#3506]
In Heptapod by @mattip on Jul 5, 2021, 09:37

venv worked around this as reported in #2735, but now this is needed for conda.

Windows 10 has enabled symlinks for developer mode. It seems conda can use this internally to save disk space. So while os.symlink is not critical to create symlinks, os.readlink is needed to determine if someone else used symlinks. There is a ctypes [implementation of readlink](https://github.com/conda/conda/blob/248741a843e8ce9283fa94e6e4ec9c2fafeb76fd/conda/gateways/disk/link.py#L84) in conda, but it is slow.

**Comment by mattip** [comment]
It has been implemented.
