### ISSUE TITLE
ctype: Incorrect usage of ctype causes pypy crashing.

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#3523]
In Heptapod by @xxm on Jul 23, 2021, 08:28

Incorrect usage of ctype causes pypy crashing.  See the attached programs[test.py](https://pypy-attachments.s3.amazonaws.com/736937129/4b1dc3338b46945ec0341c30ee065b883063cf1b7f51612b9e3c6e67d538070d/test.py), it causes segmentation fault of PyPy.
Environment: [PyPy 7.3.5 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)] on linux

--------------------------------------
from __future__ import print_function

import ctypes

import ctypes.util

lib_location = ctypes.util.find_library('gettextpo')

gpo = ctypes.cdll.LoadLibrary(lib_location)

gpo_message = gpo.po_message_create()

source = 'foo'

print('calling po_message_set_msgid')

gpo.po_message_set_msgid(source, source.encode('utf-8'))

print('success')

---------------------------------------

**Comment by mattip** [comment]
Closing as unfixable.
