### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#3700]
In Heptapod by @QonDonion on Mar 11, 2022, 08:53

I import the Pypy
and then I run something
and then it
![Screenshot_1210](https://pypy-attachments.s3.amazonaws.com/736937129/4daaf99bc0ac49a8b66ec323ef1489918fd124ed9fe86686a000afa734864225/Screenshot_1210.png)
on me :(

**Comment by mattip** [comment]
Closing since we didn't get more information. Please reopen if the problem still appears or open a new issue.
