### ISSUE TITLE
PyPy 7.3 fails to build on 32-bit Fedora with OperationError: SyntaxError in encodings/__init__.py

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#3701]
In Heptapod by @vstinner on Mar 12, 2022, 01:43

Building PyPy 7.3 fails on i386:

```
+ pypy2 pypy/tool/release/package.py --archive-name pypy-7.3 --builddir /builddir/build/BUILDROOT/pypy-7.3.6-3.fc36.i386//usr/lib --no-embedded-dependencies
'import site' failed
debug: OperationError:
debug:  operror-type: SyntaxError
debug:  operror-value: ("invalid syntax (expected ')')", ('/builddir/build/BUILD/pypy2.7-v7.3.6-src/lib-python/2.7/encodings/__init__.py', 38, 73, "_norm_encoding_map = ('                                              . '\n", 0))
Traceback (most recent call last):
  File "pypy/tool/release/package.py", line 404, in <module>
    retval, _ = package(*sys.argv[1:])
  File "pypy/tool/release/package.py", line 383, in package
    return create_package(basedir, options, **kwds)
  File "pypy/tool/release/package.py", line 99, in create_package
    raise OSError("Running %r failed!" % (str(pypy_c),))
OSError: Running '/builddir/build/BUILD/pypy2.7-v7.3.6-src/pypy/goal/pypy-c' failed!
```

Steps to reproduce the issue:

* Get any supported Fedora (even 34 or 35)
* Type: dnf install fedpkg mock
* Add the user to the mock group
* Type: fedpkg clone -a pypy && cd pypy
* Type: fedpkg srpm
* Type: mock -r fedora-rawhide-i386 --enablerepo=local pypy-*.src.rpm

Fedora considers dropping 32bit arches from "pypy2.7" program:
https://lists.fedoraproject.org/archives/list/python-devel@lists.fedoraproject.org/thread/OCDXJVGDH6NASIGOC5GZVXARHOC7UBQW/

Downstream Fedora issue: https://bugzilla.redhat.com/show_bug.cgi?id=2046857

**Comment by mattip** [comment]
@hroncok I am going through old issues. Is there still a problem building PyPy on Fedora, or is this report so old as to not be relevant?

**Comment by hroncok** [comment]
Hey. I've stipped byilding pypy for 32bit arches, so either way, we can close this. Thanks.

(I cannot close this issue myself, as it was created by the importer.)
