### ISSUE TITLE
PyWrapperDescrObject not fully implemented

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#3742]
In Heptapod by @mattip on May 14, 2022, 23:34

Over in Cython, I [added at toggle](https://github.com/cython/cython/pull/4694/files#diff-93b0d3e3e421b49750aae53b44163a97b0fcd5370910640ad56a4851c9f4c8c9R169) to allow setting the docstring on a `PyWrapperDescrObject` for `PyPy>=7.3.9` but there is a typo in the code: `PYPY_VERSION_HEX` instead of `PYPY_VERSION_NUM`. When I fix that typo, the `autotestdict` cython test crashes: it gets an uninitialized `PyWrapperDescrObject`.

**Comment by mattip** [comment]
The test passes, even when defining `CYTHON_UPDATE_DESCRIPTOR_DOC=1`. I am not sure we need to define `CYTHON_UPDATE_DESCRIPTOR_DOC` on PyPy, on CPython it is not defined for the limited API. But I may submit a PR to do that anywaty. Closing.
