### ISSUE TITLE
Expose PyFrame_Check and PyFrame_Type in cpyext

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#3754]
In Heptapod by @alex1 on May 29, 2022, 19:26

Currently there are a number of functions that operate on `PyFrame`, but not the `PyFrame_Check` function or the `PyFrame_Type` static.

**Comment by mattip** [comment]
We should expose `PyFrame_Type` and redo PyFrame_Check added recently as CPython does as
```
#define PyFrame_Check(op) Py_IS_TYPE((op), &PyFrame_Type)
```

**Comment by mattip** [comment]
Exposed in e31132b3e84, there may still be more fixes needed if cython and others assume valid fields are available on the frame which we do not mirror.
