### ISSUE TITLE
sandbox install issue Windows

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#3893]
In Heptapod by @jsmith173 on Feb 22, 2023, 12:42

I've downloaded the Win64 binary package (pypy3.9-v7.3.11-win64.zip) also I've the pypy source code (zip). Both are extracted to a different directory. Now I'm trying to follow the sandbox install from https://doc.pypy.org/en/latest/sandbox.html

The batch file I'm executed 
@setlocal  
@set PYPY=d:\Programs\pypy3.9-v7.3.11-win64  
@"%PYPY%\pypy.exe" ..\\..\\rpython\\bin\\rpython -O2 --sandbox targetpypystandalone.py  

The error message  
"my path ..\rpython"  
line 17  
    print __doc__  
    ^  
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(__doc__)?

**Comment by mattip** [comment]
Closing as won't fix. We will not support the sandbox features on windows.
