### ISSUE TITLE
PyPy 2.7-v7.3.11-win64 on Windows 10 Enterprise, Module not found

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#3946]
In Heptapod by @cappy2112 on May 30, 2023, 22:06

I'm trying PyPy for the first time on Python 2.7.

We have large, complex Python 2.7 codebase which is slowly being ported to Python 3.
After downloading 2.7-v7.3.11-win64 and adding it to the Windows path, I've tried running one of our applications
which requires a locally-developed C++ extension module. **The module is easily imported in CPython 2.7.15**,
but when running with PyPy "ImportError: No module named XXX" is displayed instantly.
(where XXX is the name of our extension module).

Our codebase requires a complex environment which includes a proprietary driver and hardware, so I cannot
simply upload an example program.

I've also tried --jit off, nothing changed.

If you have some additional steps to help debug this, I'm willing to try them.

Removing 2.7-v7.3.11-win64 from the Windows path and executing our application in a **new** cmd prompt window/shell
with Cpython 2.7.15 successfully loads the module referenced above, the application runs normally.

Thanks

**Comment by mattip** [comment]
Closing as stale. Please reopen or open a new issue if more information is needed.
