### ISSUE TITLE
pypy3.9-v7.3.9 environment using numpy1.22.3 fails

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#3954]
In Heptapod by @max-zhengtro on Jun 20, 2023, 07:01

**Before**： 
- pypy：pypy3.9-v7.3.9-linux64.tar. bz2 
- numpy：1.22.3 

numpy works fine in the environment

**Now**： 
- pypy：pypy3.9-v7.3.9-linux64.tar. bz2 
- numpy：1.22.3 

numpy does not work in the environment

error message

```
File "", line 1, in 
File "/usr/local/pypy3.9-v7.3.9-linux64/lib/pypy3.9/site-packages/numpy/__init__.py", line 152, in 
from .  import random
File "/usr/local/pypy3.9-v7.3.9-linux64/lib/pypy3.9/site-packages/numpy/random/__init__.py", line 180, in 
from .  import _pickle
File "/usr/local/pypy3.9-v7.3.9-linux64/lib/pypy3.9/site-packages/numpy/random/_pickle.py", line 1, in 
from .mtrand import RandomState
ImportError: /usr/local/pypy3.9-v7.3.9-linux64/lib/pypy3.9/site-packages/numpy/random/mtrand.pypy39-pp73-x86_64-linux-gnu. so: undefined symbol: PyInterpreterState_GetID
```

Did not find any change in pypy and numpy, but the phenomenon is that before numpy can be used normally, now the same environment can not be used, if you know why please tell, that will certainly help me a lot!

**Comment by mattip** [comment]
There is nothing we can do with such old versions of software. Please update.
