### ISSUE TITLE
Pypy segfaults during pytest test rewriting

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#3959]
In Heptapod by @LilyFoote on Jul 7, 2023, 11:08

For a while now I've been seeing pypy segfault in CI fairly frequently on a work project. A few days ago I reported this to the pytest issue tracker: https://github.com/pytest-dev/pytest/issues/11168

Since then, I have further investigated the issue and have reached this reproduction: https://github.com/LilyFoote/pypy-segfault/tree/61ca92436b75bbd4dd5690b31aa5c780512fa04d which triggered the segfault here: https://github.com/LilyFoote/pypy-segfault/actions/runs/5484866146/jobs/9993059068

I have not been able to reproduce the segfault locally or on github actions own `ubuntu-latest` runner, so I think the hardware used for the `buildjet-2vcpu-ubuntu-2204` runner may be relevant. Unfortunately the information about the hardware is pretty sparse: https://buildjet.com/for-github-actions/docs/runners/hardware

The test that causes the segfault is usually `test_get_sync`, but I have seen one run where the first three (`test_get_sync`, `test_get_streaming_response` and `test_get_binary_response`) all failed.

**Comment by mattip** [comment]
I think this is solved by the gc arraycopy fixes in #4928. Please reopen or open a new issue if the problem returns.
