### ISSUE TITLE
Syntax error rpython with print statement

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#3973]
In Heptapod by @Rhvarrier on Jul 27, 2023, 19:28

I want to build pypy from source and as described in [the docs](https://doc.pypy.org/en/latest/build.html), I executed the following command:
`pypy ../pypy_src/rpython/bin/rpython --opt=2`

However this results in the following error
`pypy_src/rpython/bin/rpython", line 17
    print __doc__
    ^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(__doc__)?
`

I also tried `python3 ../pypy_src/rpython/bin/rpython --opt=2` which results in the same issue.

Am I doing something wrong ?

My build environment is:

OS: Ubuntu 22.04 LTS

python version 3.10.12

pypy version 3.10.12

C compile gcc 11.3

I'm using tag release-pypy3.10-v7.3.12

**Comment by mattip** [comment]
Closing, thanks for trying rpython and pypy
