### ISSUE TITLE
How are translation backends for PyPy written?

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#3998]
In Heptapod by @TheShermanTanker on Sep 11, 2023, 03:52

Hi all,

Not sure if this is the right place for this, since this is not a technical issue, but I've always wondered how the translation backends (ok well, the one single backend) for PyPy are (is) written. From what I can see it collects the graphs into nodes which contain C code, then stuffs those nodes into C files? I've always wanted to write my own translation backend for PyPy for fun, but couldn't really figure out the things required just by looking at the C backend :P

**Comment by mattip** [comment]
Closing, as this is a more general discussion than an actual issue with RPython and the OP has decided not to use RPython.
