### ISSUE TITLE
pypy.exe -m ensurepip does not work when invoked from inside Windows Services for Linux

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#4003]
In Heptapod by @tekknolagi on Sep 24, 2023, 20:41

(posted on behalf of Andi McClure)

I use WSL (Windows Services for Linux) as my command line shell on Windows 10. I use basic tools such as grep, git etc inside WSL; for coding tools such as Rust cargo, Python, etc I usually (since WSL has some limitations) install Windows versions and invoke the Windows .exes from the Linux command line, which works fine, I just have to manually type the .exe at the end when I invoke them. In this respect I basically use WSL as if it were MSYS.
Today I decided to install Pypy. I downloaded the Win64 .zip and unzipped it to a convenient location. I then of course needed to run pip to install some modules. Pip was not included, but a helpful message in the interpreter, as well as [the Pypy documentation](https://doc.pypy.org/en/latest/install.html), recommended to run pypy with `-m ensurepip` to install a pip. Fine.

When I did this, I got a long and unhelpful exception, ending with "The parameter is incorrect".

![image](https://pypy-attachments.s3.amazonaws.com/736937129/59ad5bead0442168dcae117f2f16cd68b9ef9faee04ee3328f64dfa16985beef/image.png)

After wasting some time fiddling, it occurred to me that WSL could be somehow causing the problem, so I tried the command in a Windows CMD.EXE shell. This worked on the first try:

```
C:\Users\Andi>work\usr\pypy3.10-v7.3.12-win64\pypy.exe -m ensurepip
Looking in links: c:\Users\Andi\AppData\Local\Temp\tmpue1h28og
Processing c:\users\andi\appdata\local\temp\tmpue1h28og\setuptools-65.5.0-py3-none-any.whl
Processing c:\users\andi\appdata\local\temp\tmpue1h28og\pip-23.0.1-py3-none-any.whl
Installing collected packages: setuptools, pip
  WARNING: The scripts pip3.10.exe and pip3.exe are installed in 'C:\Users\Andi\work\usr\pypy3.10-v7.3.12-win64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-23.0.1 setuptools-65.5.0
```

### Expected behavior

Once an exe has been invoked inside WSL, it's just a normal Windows app running on normal Windows. So pypy should work the same if invoked from WSL Bash as if invoked from CMD.EXE, especially for a basic/"install process" kind of task like `-m ensurepip`.

If basic pypy functionality like ensurepip requires something special about the environment in which it is run— it's possible for example that my WSL was somehow creating janked environment variables, I don't know— then it should print a more helpful error message than "invalid parameter", and the environment requirements should be documented in the install instructions.

### Configuration

I am using Windows 10 Version 10.0.19045 Build 19045. My WSL is a WSL1 VM running Ubuntu 20.04.6 LTS. My pypy is pypy3.10-v7.3.12-win64. I have a file in which I have saved a copy of os.environ of pypy when invoked from WSL and a copy of same when invoked from CMD.EXE, in case this is helpful for debugging this error, but I would prefer not to post this file on a public bug report for privacy reasons.

**Comment by mattip** [comment]
We don't have a fix for this yet, I will mark it for v7.3.15. @nulano do you think you could take a look?

**Comment by nulano** [comment]
I think I've got a potential fix written.

I've added both an apptest (which passes) and an extra_tests test (not tested, I haven't run a translation yet).

What is the current procedure for testing?
I assume the buildbots are not yet migrated to the Git repo, so I can only test locally?

**Comment by mattip** [comment]
Buildbots are functional against this repo. You can push a branch here and then kick off a build. I am struggling a bit with the nightly build polling, but will be manually kicking off builds until I get the automation working.

**Comment by nulano** [comment]
I've pushed the changes to https://github.com/nulano/pypy/tree/sys_executable.

I don't think I have permissions to push to this repo, can the buildbots run off a fork?

**Comment by mattip** [comment]
I think a possible strategy would be to submit a PR which will trigger a github action to translate, you could then download the artifact. But for windows we will need to add that to the [workflow matrix](https://github.com/pypy/pypy/blob/85125f6a15ed3a7ceda83001f50c60a84380a5c1/.github/workflows/translate.yml#L20) which currently only builds linux x86_64.

> I don't think I have permissions to push to this repo

See the invite.

**Comment by nulano** [comment]
Ok, I've pushed to `branch/issue4003` and ran the buildbots - looks OK.
See PR #4828.
