### ISSUE TITLE
Windows + asyncio: AttributeError: 'Overlapped' object has no attribute 'WSARecvFrom'

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#4008]
In Heptapod by @me-asri on Oct 1, 2023, 21:18

Hello,
When using `asyncio.DatagramProtocol` I'm getting an `AttributeError` exception complaining about `WSARecvFrom` method missing from `Overlapped` class.

[Example code](https://gist.github.com/me-asri/5a5d086ee24fa7b5add80b17895bc5ef)

---

Traceback:
```
ERROR:asyncio:Exception in callback _ProactorDatagramTransport._loop_reading()
handle: <Handle _ProactorDatagramTransport._loop_reading()>
Traceback (most recent call last):
  File "C:\Users\Me\scoop\apps\pypy3\current\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Me\scoop\apps\pypy3\current\Lib\_contextvars.py", line 44, in run
    return callable(*args, **kwargs)
  File "C:\Users\Me\scoop\apps\pypy3\current\Lib\asyncio\proactor_events.py", line 573, in _loop_reading
    self._read_fut = self._loop._proactor.recvfrom(self._sock,
  File "C:\Users\Me\scoop\apps\pypy3\current\Lib\asyncio\windows_events.py", line 508, in recvfrom        
    ov.WSARecvFrom(conn.fileno(), nbytes, flags)
AttributeError: 'Overlapped' object has no attribute 'WSARecvFrom'. Did you mean: 'WSARecvInto'?
```

OS:
```
Windows 11 Education 22H2
```

PyPy:
```
Python 3.10.13 (f1607341da97ff5a1e93430b6e8c4af0ad1aa019, Sep 28 2023, 05:42:24)
[PyPy 7.3.13 with MSC v.1929 64 bit (AMD64)] on win32
```

**Comment by mattip** [comment]
Found one: conda-forge/aiohttp-feedstock#81 is failing because they use `TransmitFile`.

**Comment by mattip** [comment]
It turns out CPython now has a test for this, it is failing on the buildbot in the lib-python tests on py3.9. They must have been added in one of the stdlib updates.

**Comment by mattip** [comment]
I made some progress in 9c108f0146, but there is still more to do.

**Comment by mattip** [comment]
I think I have gone as far as I can go. There are still test failures when running `pypy3.10-c.exe -m test.test_asyncio` but no missing implementations. It now shows `FAILED (failures=1, errors=3, skipped=869)`, among those
- an Error `OSError: [WinError 996] Overlapped I/O event is not in a signaled state`
- `test_create_datagram_endpoint` raises a `asyncio.exceptions.TimeoutError`
- `test_create_datagram_endpoint_ipv6` raises a `asyncio.exceptions.TimeoutError`
- ` test_drain_raises` raises a `OSError: [WinError 10054] An existing connection was forcibly closed by the remote host`
- `test_start_tls_client_corrupted_ssl` fails with `AssertionError: SSLError not raised`

On the nightly buildbots, the tests are also failing on linux64, `FAILED (errors=6, skipped=878)`. The errors are in
- `test_create_ssl_connection` (in both `EPollEventLoopTests` and `PollEventLoopTests`)
- `test_create_ssl_unix_connection`

in all three of
- `EPollEventLoopTests`
- `PollEventLoopTests`
- `SelectEventLoopTests`
These don't fail on windows, so there is something missing.
