### ISSUE TITLE
Forgotten (?) print statement in the ssl module in pypy3.10-v7.3.13

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#4009]
In Heptapod by @nawarnoori on Oct 3, 2023, 12:43

This rogue print statement caused us issues in a few places, I tracked it down to [here](https://foss.heptapod.net/pypy/pypy/-/blob/branch/release-pypy3.10-v7.x/lib_pypy/_cffi_ssl/_stdssl/__init__.py?ref_type=heads#L1539).

**Comment by jpmckinney** [comment]
Installing via [actions/setup-python](https://github.com/actions/setup-python) in a GitHub Actions workflow.
