### ISSUE TITLE
universal newlines edge case: trailing \r\r treated as a single newline

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#4037]
In Heptapod by @dairiki on Nov 23, 2023, 07:11

I just stumbled across this by chance:

```py
>>>> import io
>>>> io.TextIOWrapper(io.BytesIO(b"\r\r"), newline="").readlines()
['\r\r']  # wrong — this should be read as two lines
>>>> io.TextIOWrapper(io.BytesIO(b"\r\r\r\r"), newline="").readlines()
['\r', '\r', '\r\r']  # this should be four lines
>>>> io.TextIOWrapper(io.BytesIO(b"a\r\rb\r\r"), newline="").readlines()
['a\r', '\r', 'b\r\r']
>>>> io.TextIOWrapper(io.BytesIO(b"a\r\rb\r\rc"), newline="").readlines()
['a\r', '\r', 'b\r', '\r', 'c']  # ← this one is correct
```

I see the same behavior with both `pypy3.9-7.3.13` and `pypy3.10-7.3.13` (installed via pyenv)

The same bug happens when reading from a file.

It only happens with `newline=""` (*universal newlines* without newline translation).  If `newline` is set to `None`, things seem to work as they are supposed to.

**Comment by mattip** [comment]
Closing, should be fixed. Please open a new issue if needed.
