### ISSUE TITLE
cpyext METH_FASTCALL and limited API

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#4050]
In Heptapod by @karlotness on Dec 28, 2023, 04:52

It looks like there is an issue with the limited API guard around `METH_FASTCALL` in `methodobject.h` which should be part of the limited API in Python 3.10.

The [current PyPy version](https://foss.heptapod.net/pypy/pypy/-/blob/branch/py3.10/pypy/module/cpyext/include/methodobject.h?ref_type=heads#L30) requires `0x03100000` while the [version in CPython 3.10](https://github.com/python/cpython/blob/b6535ea7ecf40c51a9a13089d961c29abeaffa5e/Include/methodobject.h#L82) uses `0x030A0000`. It looks like that might have been a CPython mistake that got imported into PyPy since it was fixed in the linked commit.

Very minor problem but it would be nice to have the inconsistency fixed since does cause some build issues.

**Comment by mattip** [comment]
@karlotness would you like to submit a PR to fix this (surprise: [we moved to GitHub](https://www.pypy.org/posts/2023/12/pypy-moved-to-git-github.html))? You can target the py3.10 branch.

**Comment by karlotness** [comment]
Happy to, I've added a PR now that should make the change. That is a nice new year's surprise, and I appreciate the pointer to the right branch to edit.

Thanks!

**Comment by mattip** [comment]
Fixed in #4818
