### ISSUE TITLE
recent rpython work broke existing tests

### ISSUE THREAD

**Issue by mattip** [pypy/pypy#4836]
I see a nightly build has [new failures](https://buildbot.pypy.org/summary?branch=main): something about unicode no longer raising. @olliemath could you take a look?

**Comment by mattip** [comment]
Strangely, the failure does not show up [on windows](https://buildbot.pypy.org/summary?builder=own-win-x86-64&branch=main)

**Comment by olliemath** [comment]
Ah, about to catch a flight so might not be able to look for a bit

Yes I fixed a ValueErrror raised in one of the rpython tests (the test
asserted that casting -1 to unicode and back to long gave either
sys.maxunicode or -1) but it was failing because a value error was raised
when run under pypy

This test looks like it expects the opposite semantics: a ValueError to be
raised for out of range integers. I suspect only one or other of the tests
can pass and the other should be skipped or xfailed

I guess the previous behaviour was the expected behaviour .. so we should
just revert my "fix" and skip the failing rpython test

**Comment by mattip** [comment]
Not critical, it can wait.

I am not sure we should be expecting the ValueError: I don't see any other effects of this change. If raising was desired behaviour, I would expect to see more failures. I merged to py3.9 let's see if anything new fails

**Comment by olliemath** [comment]
Ah true - cpython2 doesn't raise a ValueError with this snippet - I assume compatibility with what cpython does is the desired behaviour:

```python
>>> from array import array
>>> input_unicode = u'\x01\u263a\x00\ufeff'
>>> a = array('u', input_unicode)
>>> b = array('u', input_unicode)
>>> b.byteswap()
>>> assert b[2] == u'\u0000'
>>> assert a != b
>>> b.itemsize
4
>>> b[0]
u'\U01000000'
```

So I think we should fix that test to check the cpython behaviour

**Comment by mattip** [comment]
When merging thi with py3.9 there is a [new untranslated failure](https://buildbot.pypy.org/summary/longrepr?testname=AppTestUnicodeObject.%28%29.test_invalid&builder=own-linux-x86-64&build=10020&mod=pypy.module.cpyext.test.test_unicodeobject). The same test passes after translation. I am fine if we adjust the tests to all pass and call it a corner-case incompatibility.

**Comment by olliemath** [comment]
So playing around with python3 it _does_ raise a ValueError here (namely `ValueError: character U+1000000 is not in range [U+0000; U+10ffff]` ) - my current plan is to revert the rpython commit and change the test in a slightly different way

**Comment by mattip** [comment]
Since https://github.com/pypy/pypy/commit/6906755fd224311b8fde103d6654b8163084c96d only affects ll2ctypes, it is only seen untranslated.

**Comment by mattip** [comment]
Did this might have [broken py3.10](https://github.com/pypy/pypy/actions/runs/7466932227/job/20319376709#step:5:627) tests as well?

**Comment by mattip** [comment]
> I think I can make the test pass or else revert the commit. Neither way is 100% compatible with cpython.

@olliemath it is not just one test. I think this broke many things untranslated:
- Python2.7 untranslated
  [test__rawffi](https://buildbot.pypy.org/summary/longrepr?testname=AppTestFfi.%28%29.test_unicode_array&builder=own-linux-x86-64&build=10027&mod=pypy.module._rawffi.test.test__rawffi)
  [test__rawffi](https://buildbot.pypy.org/summary/longrepr?testname=AppTestFfi.%28%29.test_wcharp2rawunicode&builder=own-linux-x86-64&build=10027&mod=pypy.module._rawffi.test.test__rawffi)
  [test_array](https://buildbot.pypy.org/summary/longrepr?testname=AppTestArray.%28%29.test_unicode_outofrange&builder=own-linux-x86-64&build=10027&mod=pypy.module.array.test.test_array)

- Python3.9
  [cpyext test_unicodeobject](https://buildbot.pypy.org/summary/longrepr?testname=AppTestUnicodeObject.%28%29.test_invalid&builder=own-linux-x86-64&build=10028&mod=pypy.module.cpyext.test.test_unicodeobject)

It doesn't seem to have broken 3.10 (beyond the tests from 3.9)
