### ISSUE TITLE
Signature of many builtin types changed in PyPy 7.3.14

### ISSUE THREAD

**Issue by Zac-HD** [pypy/pypy#4839]
Reporting a regression I noticed in https://github.com/HypothesisWorks/hypothesis/pull/3828:

```python
from hypothesis.strategies import from_type

from_type(zip).example()  # or `AssertionError`, or many other exception types
```

This now emits a `hypothesis.errors.SmallSearchSpaceWarning` under `pypy3.9-7.3.14` and `pypy3.10-7.3.14`, but worked fine under 7.3.13 and continues to work under CPython.

I'm pretty sure that this is caused by a change in `inspect.signature(...).parameters`, and so haven't taken the time to set up all the local environments I'd need to dig further.  Let me know if you need more information and I'll be happy to try for a smaller repro.

**Comment by cfbolz** [comment]
the change is that `insgect.signature` now returns a result, as opposed to raising an exception.

before:

```pycon
>>>> import inspect
>>>> inspect.signature(zip)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cfbolz/bin/pypy3.10-v7.3.13-linux64/lib/pypy3.10/inspect.py", line 3291, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped,
  File "/home/cfbolz/bin/pypy3.10-v7.3.13-linux64/lib/pypy3.10/inspect.py", line 3039, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
  File "/home/cfbolz/bin/pypy3.10-v7.3.13-linux64/lib/pypy3.10/inspect.py", line 2573, in _signature_from_callable
    raise ValueError(
ValueError: no signature found for builtin type <class 'zip'>
```

after:

```
>>>> inspect.signature(zip)
<Signature (*args, strict=False)>
```

I suppose the signature could be nicer and this could be `(*iterables, strict=False)` or something, but it's not wrong?

what does hypothesis do if no signature is returned?

**Comment by Zac-HD** [comment]
Ah, that's a divergence from CPython but an entirely reasonable one!

Entirely my problem to fix in Hypothesis then - currently [we catch the exception and hope/assume there are no required arguments](https://github.com/HypothesisWorks/hypothesis/blob/5c52eefe532e985f552d6a91f8d7354750588a43/hypothesis-python/src/hypothesis/strategies/_internal/core.py#L1426-L1452).  Apologies for the churn, and thanks for all your work on PyPy!
