### ISSUE TITLE
Repackaging using `git archive` does not compress

### ISSUE THREAD

**Issue by mattip** [pypy/pypy#4861]
The source tarballs released in 7.3.15 are not compressed. Apparently `git archive xxx.tar.gz` creates a tar archive but does not compress it.

**Comment by mattip** [comment]
The code that packages the sources starts here https://github.com/pypy/pypy/blob/97ca8ac37da68085081aa4ba001b8e0011d877c0/pypy/tool/release/repackage.sh#L135

**Comment by edgarrmondragon** [comment]
Hey @mattip!

I think the source archives `pypy3.10-v7.3.15-src.tar.bz` and `pypy2.7-v7.3.15-src.tar.bz2` had their checksums updated but the files were not. That is, the downloaded archives still have the old checksums and are not bzip2.

**Comment by mattip** [comment]
> the downloaded archives still have the old checksum

Are they being cached somehow? https://downloads.python.org/pypy/ is showing the newer tarballs.

**Comment by edgarrmondragon** [comment]
> > the downloaded archives still have the old checksum
> 
> Are they being cached somehow? https://downloads.python.org/pypy/ is showing the newer tarballs.

Perhaps... I just downloaded [pypy3.10-v7.3.15-src.tar.bz2](https://downloads.python.org/pypy/pypy3.10-v7.3.15-src.tar.bz2) and I can confirm the checksum is still the old one:

```
$ wget -q https://downloads.python.org/pypy/pypy3.10-v7.3.15-src.tar.bz2
$ shasum -a 256 pypy3.10-v7.3.15-src.tar.bz2
48ce19ca7642131b8468ddfb7ef355f49952518702ab501e2c6b3d9b4eb09ad4  pypy3.10-v7.3.15-src.tar.bz2
```

**Comment by mattip** [comment]
Wow, this is bizzare. When I look at https://downloads.python.org/pypy/pypy*-v7.3.15-src.tar.bz2 the file sizes are ~20MB, but the link points to the old file which is ~100MB. Thanks for tracking this down. So the caching is somehow being done at the CDN level. The original files are at https://buildbot.pypy.org/pypy/, which are the correct ones. Then python.org mirrors that location across a CDN, which seems to be caching the wrong file :(

**Comment by mattip** [comment]
Using a hint from the PyPy IRC channel, I used
```
curl -X PURGE https://downloads.python.org/pypy/pypy2.7-v7.3.15-src.tar.bz2
curl -X PURGE https://downloads.python.org/pypy/pypy3.10-v7.3.15-src.tar.bz2
curl -X PURGE https://downloads.python.org/pypy/pypy3.9-v7.3.15-src.tar.bz2
```

and now the download is the right one for me. @edgarrmondragon did it also fix it for you?

**Comment by edgarrmondragon** [comment]
> and now the download is the right one for me. @edgarrmondragon did it also fix it for you?

@mattip yes, that did it! Thanks 😄

**Comment by mattip** [comment]
Sorry for the mess. Reclosing the issue.
