### ISSUE TITLE
Is there a way to get pypy installed GLOBALLY in anaconda3? 

### ISSUE THREAD

**Issue by sudo-000** [pypy/pypy#4863]
I don't want to install all the packages once again in the new environment. Can I just have pypy installed globally? 
Or, is there a way I can bulk copy packages from the global environment? 

(Note: My OS is Windows 11 21H2)

**Comment by mattip** [comment]
By design, conda environments are isolated from eachother and do not share packages.

**Comment by mattip** [comment]
Closing, since this was more of a question than an issue.
