### ISSUE TITLE
top-level __init__.py causes import error

### ISSUE THREAD

**Issue by mattip** [pypy/pypy#4885]
As reported in https://github.com/conda-forge/pycalphad-feedstock/pull/55, somehow pytest is catching the wrong error being raised here https://github.com/pypy/pypy/blob/1fca5847f1902f76523d805ed291763b23733ccb/lib_pypy/__init__.py#L3-L4

The easiest fix is to delete the file when packaging pypy

**Comment by mattip** [comment]
Closed by #4887

**Comment by h-vetinari** [comment]
Any idea when this might make it into a release? We keep hitting this in various feedstocks... We could also backport #4887 on the feedstock directly, if that's easier.
