### ISSUE TITLE
Py_UNICODE_ISALNUM and similar should take Py_UCS4 but take Py_UNICODE instead

### ISSUE THREAD

**Issue by ngoldbaum** [pypy/pypy#4901]
See e.g. https://github.com/pypy/pypy/blob/a964c5a891c8168fc3e3128bad6257546d362455/pypy/module/cpyext/unicodeobject.py#L131-L132

But in the CPython header:
https://github.com/python/cpython/blob/590319072773bd6cdcca655c420d3adb84838e96/Include/cpython/unicodeobject.h#L691

See also https://github.com/ngoldbaum/pypy-bug which contains a runnable example based on a cython script to test for the bug. When I build it on 64 bit windows pypy3.10, I see in the compiler output:

```
test_cython.c(2362): warning C4304: 'function': truncation from 'Py_UCS4' to 'wchar_t'
```

Discovered in a new test added to NumPy: https://github.com/numpy/numpy/pull/25791

**Comment by mattip** [comment]
Fixed in #4904
