### ISSUE TITLE
cpyext: spurious memory corruption involving ``PyModule_GetName``

### ISSUE THREAD

**Issue by wjakob** [pypy/pypy#4902]
Dear @mattip,

I've been chasing down some undefined behavior / memory corruption and managed to track it to a use of the function `PyModule_GetName`. In CPython, this function returns a string of type `const char *` that stays alive as long as the Python type object exists.

I suspect that in PyPy it may return a string that is very short-lived or perhaps already invalid so that subsequent use of this string in a Python API call (e.g. in `PyUnicode_FromFormat("%s ...", str);` causes undefined behavior). I don't have a nice reproducer this time (occurs as part of a larger application), but perhaps it is easy for you to see if that suspicion checks out?

Thanks,
Wenzel

**Comment by wjakob** [comment]
Never mind, further testing shows it must be something else.

**Comment by wjakob** [comment]
(reopened with clarifications)

**Comment by mattip** [comment]
Here is the note at the beginning of `PyModule_GetName`: https://github.com/pypy/pypy/blob/582c75961c889f87ced5cb163e0e1bd678b08558/pypy/module/cpyext/modsupport.py#L226-L234

Do you know how the module is being created? Perhaps some assumptions that were valid when this note was written 8 years ago are no longer valid

**Comment by wjakob** [comment]
Could it be that the very act of calling `PyModule_GetName` on a module somehow corrupts its name? The issue I've encountered is that a piece of code that calls `PyModule_GetName` causes global changes where suddenly the  `__module__` member of functions within that module is corrupted (the first letter changed from 't' to 's' 😮). It's specifically the C-string associated with the `__module__` member that shows this modification, printing in Python still shows the right value.

**Comment by mattip** [comment]
I guess the best alternative would be to implement `PyModule_GetNameObject` and then you could just do like CPython. Of course that does not excuse corrupting the value.

**Comment by mattip** [comment]
I don't see how we would be modifying the underlying C string, but obviously we are. Is it always converting `t` to `s`? Does it take much time to occur in the larger app?

**Comment by mattip** [comment]
@wjakob BTW, a PR to set up weekly testing of PyPy 3.9/3.10 against nanobind in https://github.com/pypy/binary-testing would be welcome.

**Comment by wjakob** [comment]
Sorry about the noise, this bug was my fault. The alternative code path for PyPy ran Py_DECREF() on the C-string (argh!). That also explains the one-letter change for characters that are next to each other in their ASCII representation. Thank you for adding `PyModule_GetNameObject`, that will remove the need for the alternative path in the future.

About weekly testing: I remember specifically adding such a workflow (https://github.com/pypy/binary-testing/actions/runs/7945962870). Or am I confused?
