### ISSUE TITLE
PyPy 3.10 cannot build on Windows

### ISSUE THREAD

**Issue by TheShermanTanker** [pypy/pypy#4913]
I'm getting a build failure during the annotation process every time I try to build PyPy on my Windows device:
```
[translation:ERROR] CompilationError: CompilationError(err="""
        LINK : fatal error LNK1104: cannot open file 'c:\users\vertig0\appdata\local\temp\usession-unknown-88\gcctest.exe'
        """)
```
The associated command line for building PyPy was:
`C:\Users\vertig0\Downloads\pypy-c\pypy-c.exe ../../rpython/bin/rpython --no-translation-jit --opt=mem targetpypystandalone.py --withoutmod-pypyjit --withoutmod-_jitlog --withoutmod-cpyext --withoutmod-_hpy_universal --withoutmod-_cppyy`

This error is persistent and I cannot seem to figure out why link.exe cannot open the file for whatever operation it needs to carry out

**Comment by mattip** [comment]
Is this still relevant? In general, I would suggest using linux64 rather than windows. I will close this for now, please reopen or open a new issue with
- what version of msvc are you using
- upload a complete log file.
