### ISSUE TITLE
`str.expandtabs()` does not handle Unicode characters correctly (counts UTF-8 bytes?)

### ISSUE THREAD

**Issue by mgorny** [pypy/pypy#4920]
```
$ python3.10 -c 'print("a♯\ttest".expandtabs())'
a♯      test
$ pypy3.10 -c 'print("a♯\ttest".expandtabs())'
a♯    test
```

I guess it's 2 spaces short because `♯` is 3 bytes in UTF-8.

Per CPython docs, I suppose PyPy's behavior is incorrect:
> Any other character is copied unchanged and the current column is incremented by one regardless of how the character is represented when printed.
>
> https://docs.python.org/3/library/stdtypes.html#str.expandtabs

Originally reported as https://github.com/facelessuser/pymdown-extensions/issues/2324.

**Comment by cfbolz** [comment]
ouch, that's embarrassing. I'm fixing it.

**Comment by cfbolz** [comment]
turns out that expandtabs was also quadratic :grimacing:. fixed for pypy2, merging to pypy3 now

**Comment by cfbolz** [comment]
merged, thanks for the report @mgorny!

**Comment by mgorny** [comment]
Thanks!
