### ISSUE TITLE
[pypy3.9-7.3.11] `concurrent.futures.process.py` bug

### ISSUE THREAD

**Issue by algo-1** [pypy/pypy#4922]
I tried to use the process pool executor and got an attribute error. I fixed it locally by changing the `self._adjust_process_count()` in the `submit` function to `self._adjust_process_count_cpython()` as the former did not exist in the `process.py` file and this fixed the issue.

```python
def submit(self, fn, /, *args, **kwargs):
        with self._shutdown_lock:
            if self._broken:
                raise BrokenProcessPool(self._broken)
            if self._shutdown_thread:
                raise RuntimeError('cannot schedule new futures after shutdown')
            if _global_shutdown:
                raise RuntimeError('cannot schedule new futures after '
                                   'interpreter shutdown')

            f = _base.Future()
            w = _WorkItem(f, fn, args, kwargs)

            self._pending_work_items[self._queue_count] = w
            self._work_ids.put(self._queue_count)
            self._queue_count += 1
            # Wake up queue management thread
            self._executor_manager_thread_wakeup.wakeup()

            if self._safe_to_dynamically_spawn_children:
                self._adjust_process_count_cpython()    # affected line
            self._start_executor_manager_thread()
            return f
    submit.__doc__ = _base.Executor.submit.__doc__
   ```

**Comment by algo-1** [comment]
It appears to be fixed in the latest https://github.com/pypy/pypy/blob/release-pypy3.9-v7.x/lib-python/3/concurrent/futures/process.py. However, I am not sure if patches are made to specific versions in pypy.

**Comment by mattip** [comment]
That was part of the sync to stdlib 3.9.15. [PyPy 7.3.10 supports that version](https://doc.pypy.org/en/latest/release-v7.3.10.html) and was released in Dec 2022. Please update to the latest PyPy - 7.3.15.
