### ISSUE TITLE
nanobind tests lead to gc invariant violation

### ISSUE THREAD

**Issue by cfbolz** [pypy/pypy#4925]
I've been investigating a bug reported by @wjakob [here](https://github.com/orgs/pypy/discussions/4923). it happens as random crashes on github ci. to reproduce it:

```
git clone --recursive git@github.com:wjakob/nanobind.git
cd nanobind
pypy3.10 -m venv venvpypy310
. venvpypy310/bin/activate
pip install pytest pytest-github-actions-annotate-failures typing_extensions
cmake -S . -B build -DNB_TEST_STABLE_ABI=ON -DNB_TEST_SHARED_BUILD="$(python3 -c 'import sys; print(int(sys.version_info.minor>=11))')"
cmake --build build
cd build
PYPY_GC_DEBUG=2 PYPYLOG=gc:- python --jit off -m pytest
```

**Comment by wjakob** [comment]
Excellent! Is this with some nanobind functions still on the backtrace, or after an operation (e.g. type creation)?

**Comment by cfbolz** [comment]
no, so far it actually seems mostly unrelated to nanobind? if I run it with `python -v` to print the imports, the only extension module that gets build before the crash is `_lzma`, which uses cffi.

**Comment by cfbolz** [comment]
indeed, with the pypy3.10-lldebug that I just freshly built, I can even get this to crash?!:

```
pypy3.10 -m venv venvpypy310
. venvpypy310/bin/activate
pip install pytest
PYPY_GC_DEBUG=2 PYPY_GC_NURSERY_DEBUG=1 PYPYLOG=gc:- python --jit off -c "import pytest"
```

**Comment by cfbolz** [comment]
it seems I managed to reproduce the crash in an (untranslated) unit-test of the GC. both in the form where GC debugging is turned on (then I get the assertion error) and in the form where the GC frees a still reachable object. Very annoying bug, but I'm happy to have managed to write a test.

**Comment by cfbolz** [comment]
I spent a lot more time in rr today and may have found the source of the crash (as opposed to the source of the failing invariant assert, which seems to be a different issue).

Here's a [diff](https://github.com/pypy/pypy/compare/gc-arraycopy-incrementality-bug?expand=1) for my new attempt at reproducing the problem and fixing it, @arigo, could you maybe take a look?

**Comment by arigo** [comment]
I don't really have in my mind what is needed to re-understand all the cases in `writebarrier_before_copy`.  Your comment says it's not OK to check `source_hdr.tid & GCFLAG_TRACK_YOUNG_PTRS` if `gc_state == STATE_MARKING`.  Does this mean we have the same bug [a few lines above](https://github.com/pypy/pypy/compare/gc-arraycopy-incrementality-bug?expand=1#diff-52997523e1820be72aab5f6567b907a549af4c8c45517e03f3c8fe96f05f84b5L1618)?

**Comment by cfbolz** [comment]
no, because in that case we `return False`, which means "please simply copy individual items, don't use memcopy" to the caller. the write of the individual items will use `remember_young_pointer_from_array2` for every array write (I think the reason why we introduced `writebarrier_before_copy` is to sometimes be able to avoid calling `remember_young_pointer_from_array2` many times). And `remember_young_pointer_from_array2` does not get the `source` array at all (it's called for arbitrary array writes, not just copies).

I really appreciate you looking at it, thank you!

**Comment by cfbolz** [comment]
...but now that I am writing this, I am not sure about the next if:

```python
            if source_hdr.tid & GCFLAG_CARDS_SET == 0:
                # The source object has no young pointers at all.  Done.
                return True
```

because not having young pointers could still make it possible to have "old but white" pointers.

**Comment by arigo** [comment]
Here is how I read your diff as it is now: assume that `source_hdr` does contain the flag `GCFLAG_TRACK_YOUNG_PTRS` but we are in `STATE_MARKING`.   Then, in that case, in the no-card case, we go to the path with the comment "there might be in source a pointer to a young object"; but, in the with-card case, we DON'T go to the path with the very similar comment "The source object may have random young pointers".  Is that really correct?

**Comment by cfbolz** [comment]
basically only the cases that return `True` can have a problem at all, because if `False` is returned, then the caller must not use memcopy, but individually copy every item (which will again trigger the regular array write barrier):

```python

def ll_arraycopy(source, dest, source_start, dest_start, length):
    ...
    slowpath = False
    if must_split_gc_address_space():
        slowpath = True
    elif _contains_gcptr(TP.OF):
        # perform a write barrier that copies necessary flags from
        # source to dest
        if not llop.gc_writebarrier_before_copy(lltype.Bool, source, dest, # <------- if this returns False, we take the slowpath
                                                source_start, dest_start,
                                                length):
            slowpath = True
    if slowpath:
        # if the write barrier is not supported, or if we translate with
        # the option 'split_gc_address_space', then copy by hand
        i = 0
        while i < length:
            copy_item(source, dest, i + source_start, i + dest_start) # <------- every of these writes performs a write barrier 
            i += 1
        return
    source_addr = llmemory.cast_ptr_to_adr(source)
    dest_addr   = llmemory.cast_ptr_to_adr(dest)
    cp_source_addr = (source_addr + llmemory.itemoffsetof(TP, 0) +
                      llmemory.sizeof(TP.OF) * source_start)
    cp_dest_addr = (dest_addr + llmemory.itemoffsetof(TP, 0) +
                    llmemory.sizeof(TP.OF) * dest_start)

    llmemory.raw_memcopy(cp_source_addr, cp_dest_addr,
                         llmemory.sizeof(TP.OF) * length)
    keepalive_until_here(source)
    keepalive_until_here(dest)
```

so the difference between the case that I changed, and the case that you point to is that the former returns True, making it unsafe, and the latter returns False, which means we will end up in a different write barrier `remember_young_pointer_from_array2` which does the right thing. Does that make sense?

That said, the case that I linked to in my [last comment](https://github.com/pypy/pypy/issues/4925#issuecomment-2014531033) has the same problem, I'm currently writing a test for that and it will need a fix.

I also hope to extend the random tests to also call `ll_arraycopy` to try to see whether I can reproduce the bugs.

**Comment by cfbolz** [comment]
ok, reproduced and fixed the second problem, and extended random testing to also do array copies in such a way that it would have found the bugs. will now keep it running for a few nights to see whether I can find more issues. I might also add some more features like pinning and weakrefs to the random tester.

**Comment by cfbolz** [comment]
here's the updated [diff](https://github.com/pypy/pypy/compare/gc-arraycopy-incrementality-bug?expand=1#diff-52997523e1820be72aab5f6567b907a549af4c8c45517e03f3c8fe96f05f84b5)

**Comment by cfbolz** [comment]
@arigo I'm a little bit annoyed by the ad-hocness of all these fixes. and also by how indirect the mechanism for turning black objects that are modified back into gray is: the objects are all added to some unrelated list, and then at the next collection GCFLAG_VISITED is removed, and the objects are added to `more_objects_to_trace`, to make them gray. I wonder whether all this would shouldn't instead be done directly in the slow paths of the write barrier, which might make things easier to understand.

**Comment by arigo** [comment]
OK, your change looks like it might work too.  What I had in mind was simply to copy the condition ``or gc_state == STATE_MARKING`` after the ``if source_hdr.tid & GCFLAG_TRACK_YOUNG_PTRS == 0`` line, thus making it exactly the same condition as in the non-cards case.  It would mean that in STATE_MARKING we would always return False, which is always safe.

**Comment by cfbolz** [comment]
right, that would certainly be easier to understand. it would mean that the memcopy optimization for card-marking is always disabled in marking phases (not sure that's a problem).

the random tests still show a further problem btw, but I don't understand it yet.

btw, I only now realized that `writebarrier_before_copy` is basically verbatim the same in `minimark.py`, which makes it more understandable to me how this bug happened.

**Comment by cfbolz** [comment]
I've merged the fixes now. tomorrow's nightlies should not crash anymore, I'll test that for a while and see.

**Comment by cfbolz** [comment]
@mattip:

> Cool. I guess we should think about a release

There's another (totally different) branch that I still want to merge, should get to it soon (it's about stack depth computation in the byte code compiler). But I guess we are still some way off anyway.

**Comment by mattip** [comment]
OK. There are also a number of things still in the [v7.3.16 milestone](https://github.com/pypy/pypy/milestone/20).

**Comment by mattip** [comment]
Closing. There may be more latent gc bugs, but at least this seems fixed. Please reopen if I am mistaken
