### ISSUE TITLE
Was the pypy2.7-v7.3.15 archive changed?

### ISSUE THREAD

**Issue by SMillerDev** [pypy/pypy#4930]
When Homebrew added this version, it had a checksum of `9e1a10d75eea8830f95035063e107bc7e4252a0b473407c929bf3d132ce6737f` and now it reports `a66ddaed39544a35bb7ab7a17dbf673a020c7cb3a614bd2b61a54776888daf2c` was the release retagged? Because the [git manual](https://git-scm.com/docs/git-tag#_on_re_tagging) says re-tagging is "the insane thing" to do.

**Comment by devdanzin** [comment]
Yes, see #4919.

**Comment by SMillerDev** [comment]
Thank you, my search skills clearly let me down
