### ISSUE TITLE
aarch64: cache size detection support is missing, resulting in 1MB nursery size

### ISSUE THREAD

**Issue by wash-amzn** [pypy/pypy#4939]
[get_L2cache_linux2](https://github.com/pypy/pypy/blob/2f062f614b58c1c2bb223d8c986db91ebcd61b81/rpython/memory/gc/env.py#L135) doesn't have an arm64 case, resulting in the default nursery size falling back to [1MB](https://github.com/pypy/pypy/blob/2f062f614b58c1c2bb223d8c986db91ebcd61b81/rpython/memory/gc/env.py#L441).

At least for the one pypy-using gunicorn/gevent HTTP application I've been profiling recently, this dramatically reduces performance compared to using the intended value (due to far more minor and major GCs). The easy work around is to use the ```PYPY_GC_NURSERY``` environment variable.

**Comment by mattip** [comment]
Right, the aarch64 case falls through.

**Comment by wash-amzn** [comment]
A minor related thing is that the [GC documentation](https://doc.pypy.org/en/latest/gc_info.html#environment-variables) says the default is 4MB, when in reality it's 1MB.

**Comment by mattip** [comment]
What have you found works best for you? What processor are you using? From what I can see, a 1MB L2 cache is typical, no?

**Comment by wash-amzn** [comment]
I should have mentioned it before, but that code is not actually getting L2 size, but L3 size. On a c6i EC2 instance type, that's 55MB, so the nursery size is 27MB. For a c7g (Graviton 3), the L3 is 32MB. A nursery size of 16MB (assuming we keep the documentation's statement of 1/2 last level cache) appeared pretty ideal there. On both the c6i and c7g there isn't much improvement past 16MB.

**Comment by mattip** [comment]
I raised the default value as well as the minimum value to match the documentation (4MB) and updated the documentation. Thanks for pointing it out.

**Comment by mattip** [comment]
I couldn't find a simple interface for querying the L2/L3 caches on aarch64. Maybe we could do better than `/proc/cpuinfo` ?

**Comment by wash-amzn** [comment]
```lscpu``` gives more consistent output for x86 and arm64, but that's a command not a file. I ```strace```'ed it and found that it's reading ```/sys/devices/system/cpu/cpu0/cache/index3/size``` for L3, which gives the right values

on c6i 55MB
```
[ec2-user@ip-10-0-0-94 ~]$ lscpu | grep cache
L1d cache:           48K
L1i cache:           32K
L2 cache:            1280K
L3 cache:            55296K
```
```
[ec2-user@ip-10-0-0-94 ~]$ cat /sys/devices/system/cpu/cpu0/cache/index3/size
55296K
```

on c7g 32MB
```
[ec2-user@ip-10-0-0-227 ~]$ lscpu | grep cache
L1d cache:           64K
L1i cache:           64K
L2 cache:            1024K
L3 cache:            32768K
```
```
[ec2-user@ip-10-0-0-227 ~]$ cat /sys/devices/system/cpu/cpu0/cache/index3/size
32768K
```

I cannot speak to which kernel versions and/or OS distributions that sysfs entry is available on. It might not be be ubiquitous.

**Comment by wash-amzn** [comment]
libc's [sysconf](https://man7.org/linux/man-pages/man3/sysconf.3.html) can lookup cache sizes, however it appears that is broken as well on arm (for all cache sizes, not just L3)

**Comment by wash-amzn** [comment]
For what it's worth, the .net runtime's primary source for cache sizes are those /sys files: https://github.com/dotnet/runtime/blob/3e569f5696ddf6c93e56eeaaf1703bb64e561f1b/src/coreclr/gc/unix/gcenv.unix.cpp#L865

**Comment by wash-amzn** [comment]
According to [Documentation/ABI/testing/sysfs-devices-system-cpu](https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-devices-system-cpu) , the ```/sys/devices/system/cpu/cpu*/cache/index*/size``` entries "existed before August 2008"

**Comment by mattip** [comment]
I think we can give `/sys/devices/system/cpu/cpu0/cache/index3/size` a try, if it fails we will be in the same situation as now

**Comment by mattip** [comment]
Done in 1b98d65337. It turns out there was already code to look in that path for the `ia64` processor, so I generalized it to `aarch64` as well.

Closing, please reopen if the latest nightly does not fix the issue.

**Comment by wash-amzn** [comment]
Confirmed with a build of the ```py3.9``` branch after merging from ```main```
```
root@9f1aacfec797:/app# /opt/pypy-nightly/bin/pypy3.9 -c 'import gc; print(gc.get_stats().nursery_size)'
16.5MB
```
