### ISSUE TITLE
`PyLong_AsLong` on 3.10+ should no longer use `__int__` conversion

### ISSUE THREAD

**Issue by davidhewitt** [pypy/pypy#4949]
As per https://github.com/python/cpython/issues/82180, the `__int__` method is no longer used for conversions to integer to avoid lossy float->int conversions.

In particular I am observing that `PyLong_AsLong` on PyPy 3.10 will still accept a `float` object and convert it to a C long without error, which is different to the current CPython behaviour.

I think the code which calls `__int__` and needs updating is in the following location, but I'm not familiar enough with the PyPy codebase to know for sure nor the consequences of removing `__int__` from that codepath:

https://github.com/pypy/pypy/blob/19d9fa6be11165116dd0839b9144d969ab426ae7/pypy/interpreter/baseobjspace.py#L319-L341

**Comment by mattip** [comment]
Thanks. Fixed in 986ac7d46f0. Please reopen if I missed something.

**Comment by davidhewitt** [comment]
Thanks 👍
