### ISSUE TITLE
help: how to compile pypy on solaris 11

### ISSUE THREAD

**Issue by flaajimi** [pypy/pypy#4950]
Hello,

Can anyone help me compile pypy on solaris 11 ?

Thank you :)

**Comment by mattip** [comment]
You can try to adapt the directions at https://doc.pypy.org/en/latest/build.html to your system. Let us know if there are failures.

**Comment by flaajimi** [comment]
When I try to follow the steps I get

root@XXXXXXXX:/home/XXXXXXXXXXXX/pypy-main/pypy/goal#  python ../../rpython/bin/rpython --cc=gcc --opt=2
  File "/home/zabbixagt/pypy-main/pypy/goal/../../rpython/bin/rpython", line 17
    print __doc__
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(__doc__)?

**Comment by mattip** [comment]
You must use python2 as a host for compilation. I would suggest using the JIT, since otherwise PyPy will be slow:
```
python2 ../../rpython/bin/rpython -Ojit ...

**Comment by flaajimi** [comment]
In my server i have : python3, python3.11, python3.7, python3.9

i do not have : python2


It's solaris 11 which is not compatible with python 2

**Comment by mattip** [comment]
You will have to build python2 from source, and then use that to build PyPy.
