### ISSUE TITLE
Error message for tuple indices with invalid types use to be slightly better before recent commits

### ISSUE THREAD

**Issue by SylvainDe** [pypy/pypy#4954]
**Description**

A CI issue on a project of mine (which I do not really maintain) led me to find that a recent PyPy commit changed the error message for a piece of Python such as:

`(1, 2, 3)["2"]`

As far as I can tell, the error message used to be:

> TypeError('tuple **index** must be an integer, not str',)

but is now:

> TypeError('tuple must be an integer, not str',)

As far as I can tell, the original error message explains more correctly the issue.

**Investigation**

Initial steps of the investigation are on https://github.com/SylvainDe/DidYouMean-Python/issues/65 .
As a summary:

- the original behavior corresponds to: https://github.com/pypy/pypy/commit/653c96206b8129febb6fd715fdbaf1951fad0075
- the new behavior corresponds to: https://github.com/pypy/pypy/commit/ef5fded571923fd05bca4197a174a417537887df
- that commit looks pretty innocent so I suspect that the issue is caused by https://github.com/pypy/pypy/commit/ff77b4347cc259404335a0079ea9044e5360ffdb

**Additional details**

I hope that this issue is relevant. I have not actually used the corresponding PyPy versions and merely used them in Github actions. Please let me know if you need additional details.

**Comment by mattip** [comment]
Yes, I think ff77b43 changed "tuple index" to "tuple" [here](https://github.com/pypy/pypy/commit/ff77b4347cc259404335a0079ea9044e5360ffdb#diff-a89868f7651c932952adbb3f14e977f3cd08af3adfbd0c8d4453cc2e2670652dR198). Thanks for the report and the bisecting.

**Comment by mattip** [comment]
Fixed in 06b6112a3bb. Closing, thanks again.

**Comment by SylvainDe** [comment]
This is not acceptable! I've been waiting for a fix for this very important error for 26 minutes!

Joking aside, I'm amazed by the efficiency! Thanks for your work!
