### ISSUE TITLE
Some small missing items when compared to CPython

### ISSUE THREAD

**Issue by devdanzin** [pypy/pypy#4962]
These properties are missing from PyPy 3.10 on Windows, while present on CPython 3.10:

 - ~~array.typecodes~~ 
 - ~~cmath.tau~~
 - ~~sqlite3.complete_statement~~
 - ~~sqlite3.enable_callback_tracebacks~~ 
 - ~~sqlite3.SQLITE_CREATE_VTABLE~~
 - ~~sqlite3.SQLITE_DROP_VTABLE~~
 - ~~sqlite3.SQLITE_FUNCTION~~
 - ~~sqlite3.SQLITE_RECURSIVE~~
 - ~~sqlite3.SQLITE_SAVEPOINT~~
 - token.SOFT_KEYWORD
 - ~~ssl.OP_NO_RENEGOTIATION~~
 - ~~ssl.VERIFY_X509_PARTIAL_CHAIN~~
 - ~~stat.IO_REPARSE_TAG_APPEXECLINK~~
 - ~~stat.IO_REPARSE_TAG_MOUNT_POINT~~
 - ~~stat.IO_REPARSE_TAG_SYMLINK~~

Plus a bunch of `socket` and `zlib` constants that I can list if that would help.

**Comment by mattip** [comment]
The `stat.IO_REPARSE*` constants were added in 1f46a199

**Comment by mattip** [comment]
I added the _ssl and _sqlite3 ones. As for token.SOFT_KEYWORD, I am not sure why it is not exposed in pypy/interpreter/pyparser/pytoken.py. Maybe an oversight? I also see that lib-python/3/token.py exists. I think we should delete that, it is copied from CPython and is not relevant for PyPy.

**Comment by mrdaybird** [comment]
@mattip I recently came across the issue regarding pypy's ssl module not having the `OP_NO_RENEGOTIATION` flag, nonetheless it's great to see that `ssl.OP_NO_RENEGOTIATION` is getting added to pypy. 
But do you have workaround to disabling renegotiation without this flag? FYI, RFC 9113 requires renegotiation to be disabled for HTTP/2 and it's a blocker for [urllib/3456](https://github.com/urllib3/urllib3/pull/3456)

**Comment by mattip** [comment]
You can use `OP_NO_RENEGOTIATION = 0x40000000`, that is what [I did](https://github.com/pypy/pypy/blob/421417d0bcc8953992884508b2d28a12dfe38b5e/lib_pypy/_cffi_ssl/_stdssl/__init__.py#L104)

**Comment by mattip** [comment]
> I think we should delete that, it is copied from CPython and is not relevant for PyPy.

My bad, it is needed for untranslated tests of interpreter/app_main. Restored.

**Comment by mattip** [comment]
token.SOFT_KEYWORD was added. Closing. Thanks for reporting. If there are still problems, please open a new issue.
