### ISSUE TITLE
pypy cffi _curses has check issue

### ISSUE THREAD

**Issue by georgeharker** [pypy/pypy#4967]
On a mac,

compilation will error out with tparm being assigned to an incompatible function pointer.

changing

`lib_pypy/_curses_build.py
`
`char * tparm(const char *, ...);
`
to

`char * tparm(char *, ...);"
`
resolves this issue.  I suspect this is platform specific.

**Comment by mattip** [comment]
It seems it is macos-only?

**Comment by mattip** [comment]
This was done in 13e2004 last month, and will be part of the next release.

**Comment by georgeharker** [comment]
Probably is macOS only.

**Comment by mattip** [comment]
Closing, please reopen if something is missing.
