### ISSUE TITLE
surrogateescape option to encode seems absurdly slow, makes BLOBs in pymysql unusable

### ISSUE THREAD

**Issue by mrsoftware0** [pypy/pypy#4972]
Compare evaluating the following expression in cpython and pypy:

len(('\udcdb'*400000).encode('utf8', 'surrogateescape'))

When I tried it in cpython it gave a result instantly, while on pypy on the same machine it took 9.5 minutes and was not interruptible with control-C. Pymysql uses this kind of encoding to send binary data to the server, which means BLOBs of any real size are not usable in pymysql on pypy. Also, 9.5 minutes for this seems ridiculous?

**Comment by mattip** [comment]
I can reproduce this on PyPy3.10-v7.3.16 (on macos). Even `len(('\udcdb'*20_000).encode('utf8', 'surrogateescape'))` takes a few seconds. First guess would be that we are re-allocating the string in the error-handling slow path.

**Comment by cfbolz** [comment]
yeah, it's quadratic (it's not even re-allocating the string that's the problem, but the errorhandler path does really weird stuff). I can fix it.

**Comment by cfbolz** [comment]
@mrsoftware0 can you point me to the code in pymysql that uses this kind of encoding for binary data? pypy should obviously still not be slow. but it sounds really weird to use a surrogate-escaped utf-8 encoding for non-text binary data :thinking:

**Comment by mrsoftware0** [comment]
Sure, take a look at pymysql/connections.py Connection.query(). The relevant issue happens because binary data to be written to a blob is first decoded as if it were ascii with "surrogateescape" (see pymysql/converters.py escape_bytes()) and then the result of that is passed in as part of the query string to Connection.query() which encodes it as utf8 (in my case). This looks like kind of a weird way of doing it to my eyes too, but I don't really know the pymysql code base.

**Comment by cfbolz** [comment]
the same issue exists for basically every single encoder that's implement in `unicodehelper.py` :-(

**Comment by cfbolz** [comment]
I'm (slowly) working on trying to fix this on the `py3.9-surrogateescape-slowness` branch.

**Comment by mattip** [comment]
Latest nightlies merged a change to the way unicode errorhandlers are called, could you retest?

**Comment by mattip** [comment]
Testing the binary on linux
```
time <pypy> -c "len(('\udcdb'*20_000).encode('utf8', 'surrogateescape'))"
```

the time went from 7 seconds to 0.1. Thanks for reporting. Closing, please reopen if there are more places to fix this.

**Comment by mrsoftware0** [comment]
Thanks! Sorry I didn't reply earlier but the forwarding setting on this email account seems to have gotten unset.
