### ISSUE TITLE
__future__ statements must appear at beginning of file? Is this a bug on pypy?

### ISSUE THREAD

**Issue by zzl261004** [pypy/pypy#4973]
I get this test program by fuzzing. The following code behaves differently on CPython and Pypy. This testcase works well on Cpthon. But it  reports a SyntaxError on Pypy.

test.py
```
""" Doc String """ "Extension"
from __future__ import print_function
from __future__ import unicode_literals
```

Behavior on Pypy:
```
  File "/tmp/test.py", line 2
    from __future__ import print_function
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: __future__ statements must appear at beginning of file
```

Behavior on Cpython(**3.8.12, 3.9.0, 3.10.14, 3.13.0**):
This testcase works well on different versions.

Test Environment:
Python 3.10.14 (75b3de9d9035,Apr 21 2024, 10:54:48) 
[PyPy 7.3.16 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
Operating System: Ubuntu 18.04

**Comment by cfbolz** [comment]
seems unlikely that anybody does this, given that we never got any bug reports about it
