### ISSUE TITLE
Behavior mismatch of shutil.move with copy_function shutil.copy2 on Windows. 

### ISSUE THREAD

**Issue by Erotemic** [pypy/pypy#4977]
I'm still a bit confused on exactly what is going on here. This only happens on Windows, and it has to do with using a function like `shutil.move` or `shutil.copytree` with `shutil.copy2` as the `copy_function`. Here is the MWE:

```python
    import sys
    import pathlib
    import shutil
    import os
    import stat
    import platform
    if sys.platform.startswith('win32') and platform.python_implementation() == 'PyPy':
        os.supports_follow_symlinks.add("stat")
        stat.IO_REPARSE_TAG_APPEXECLINK = 0x8000001b  # windows
        stat.IO_REPARSE_TAG_MOUNT_POINT = 0xa0000003  # windows
        stat.IO_REPARSE_TAG_SYMLINK = 0xa000000c      # windows
    user_dpath = pathlib.Path('~').expanduser()
    cache_dpath = user_dpath / 'AppData/Local/'
    tempdir = (cache_dpath / 'ubelt/tests/win32_pypy_issues' / sys.implementation.cache_tag)
    if tempdir.exists():
        shutil.rmtree(tempdir)
    tempdir.mkdir(exist_ok=True, parents=True)

    src = tempdir / 'src'
    dst = tempdir / 'does_not_exist_yet/dst'

    if dst.exists():
        shutil.rmtree(dst)
    if src.exists():
        shutil.rmtree(src)

    # Populate the source directory
    src.mkdir()
    (src / 'file1.txt').touch()
    (src / 'subdir1').mkdir()
    (src / 'subdir1/subfile1.txt').touch()

    # (src / 'flink_abs').symlink_to((src / 'file1.txt'))
    # (src / 'flink_rel').symlink_to('file1.txt')
    # (src / 'dlink_abs').symlink_to((src / 'subdir1'))
    (src / 'dlink_rel').symlink_to('subdir1')

    # Attempt to move into a non-existing directory
    if 1:
        from functools import partial
        copy_function = partial(shutil.copy2, follow_symlinks=True)
        shutil.move(src, dst, copy_function=copy_function)
    else:
        shutil.move(src, dst, copy_function=shutil.copy2)
```

On CPython 3.10 this code works fine, no issue.

On PyPy 3.9  I get an error:

```
File ~\Desktop\pypy\pypy3.9-v7.3.16-win64\Lib\shutil.py:383, in copystat(src, dst, follow_symlinks)
    381 else:
    382     st = lookup("stat")(src, follow_symlinks=follow)
--> 383 mode = stat.S_IMODE(st.st_mode)
    384 lookup("utime")(dst, ns=(st.st_atime_ns, st.st_mtime_ns),
    385     follow_symlinks=follow)
    386 # We must copy extended attributes before the file is (potentially)
    387 # chmod()'ed read-only, otherwise setxattr() will error with -EACCES.

AttributeError: 'NoneType' object has no attribute 'st_mode'
```

For what the MWE does:

The first part of it is a workaround discussed in https://github.com/orgs/pypy/discussions/4952 

Then I setup a fresh temp directory to play with and make a nested folder structure, which critically contains a symlink. It doesn't seem to matter what the details of the symlink are, I tried several commented variants.

Then the test part that really confuses me. As is (with the `if 1`) it produces the error described above. However, and only on pypy, if I change the `if 1` to an `if 0` and use the alternate route, it doesn't error. This makes no sense to me because the `copy_function` I define in the first part should exactly be `shutil.copy2`. The argument `follow_symlinks=True` is what the docs claim `copy2` is defaulting to any way.

Looking deeper in the code it does appear that it cares that the `copy_function` is a partial and not exactly the original `copy2`, evidenced by the line in shutil: `    use_srcentry = copy_function is copy2 or copy_function is copy`. 

I'm not sure exactly what's going on under the hood, but it leads to `copystat` resolving the `lookup("stat")` call to the `_nop` function, and getting `None` instead of what should be an `os.stat_result`, so asking for the `st_mode` attribute of a None object fails, and hence the error.

Not sure if there is a workaround for this or not, but there is definitely an issue given that the same code works fine in CPython.

**Comment by Erotemic** [comment]
The issue is in the `copystat` function and also has to do with the workaround used. The relvant code is:

```
        def lookup(name):
            fn = getattr(os, name, _nop)
            if fn in os.supports_follow_symlinks:
                print(f'Try to lookup (v2) {name=!r}... {fn=!r}')
                return fn
            print(f'Try to lookup (v2) {name=!r}... {_nop=!r}')
            return _nop
```

The expression `fn in os.supports_follow_symlinks` has `fn` being the actual function `os.stat`, but in the workaround we did `os.supports_follow_symlinks.add("stat")`. I am testing to see if `os.supports_follow_symlinks.add(os.stat)` works.

**Comment by mattip** [comment]
Sorry, my comment in the discussion was wrong. The end result of the patch should be
```
>>>> os.supports_follow_symlinks
{<built-in function stat>}
```

**Comment by Erotemic** [comment]
I've verified it is enough to do `os.supports_follow_symlinks.add(os.stat)`, which I believe is already fixed in the development branch, so I'll close this.
