### ISSUE TITLE
Can you share site-packages with cython?

### ISSUE THREAD

**Issue by ff781** [pypy/pypy#4978]
Even if there is no official support for this, does anyone know of or has an idea for a possibly hacky but working setup to share site-packages across my pypy and cython?

obviously packages that don't support pypy don't have to work, just the ones that do

**Comment by mattip** [comment]
You will still have to `pypy3 -m pip install` any package with a c-extension, and then carefully manage the versions between cpython and pypy. This is similar to putting cpython packages from different cpython versions together in the same site-packages, which is also strongly discouraged.
