### ISSUE TITLE
[Question] Hide "patching of [...] readlink [...]"

### ISSUE THREAD

**Issue by Commandcracker** [pypy/pypy#4981]
How do I hide/disable this message ?

`PyPy: Skipping patching of the os module as it appears the 'readlink' function has been added.`

**Comment by mattip** [comment]
More information needed.

What version of PyPy? What other packages do you have installed? What platform? What are you doing when you see this message?

**Comment by devdanzin** [comment]
Seems to come from sanic:

https://github.com/sanic-org/sanic/blob/da1c6465852c8fc0b77ee2618d845665292045e0/sanic/compat.py#L81-L95

**Comment by Commandcracker** [comment]
Oh, I'm sorry, I thought this is a message from PyPy.
