### ISSUE TITLE
Py_UNREACHABLE not defined

### ISSUE THREAD

**Issue by apmorton** [pypy/pypy#4982]
https://docs.python.org/3/c-api/intro.html#c.Py_UNREACHABLE

This symbol is not defined by pypy, which causes some native python modules to fail to compile.

Namely, https://github.com/MKuranowski/aiocsv/issues/29

**Comment by mattip** [comment]
Probably best to work around this in your code with a `#ifdef PYPY_VERSION` clause. Even if we fix this, I don't know when there will be a new release of PyPy

**Comment by mattip** [comment]
Added to py3.9 in 4feddb4b83dc9a04eab05e, thanks for pointing it out.
