### ISSUE TITLE
Wrong value of "readonly" in PyMemoryView_FromMemory

### ISSUE THREAD

**Issue by bemoody** [pypy/pypy#4992]
When a C extension calls `PyMemoryView_FromMemory`, the resulting memoryview object has its "readonly" attribute backwards: if the caller specifies `PyBUF_READ`, the object is *not* read-only, and if the caller specifies `PyBUF_WRITE`, the object *is* read-only.

(CPython 3.11 behaves as documented here: https://docs.python.org/3.11/c-api/memoryview.html#c.PyBUF_READ)

I'm guessing that the bug is the following line (`pypy/module/cpyext/memoryobject.py`, line 197):
```
    readonly = int(widen(flags) == PyBUF_WRITE)
```
which should be instead:
```
    readonly = int(widen(flags) == PyBUF_READ)
```

(For the record, I'm aware that cpyext is not the most efficient way to interface C code with PyPy, and I'm aware that PyMemoryView_FromMemory is not the best API in general; but my goal for the moment is to have something that works and is portable across many Python versions.)

## Example

`exmodule.c`:
```
#include "Python.h"

static char buf[10];

static PyObject *
ex_mview_ro_memory(PyObject *self, PyObject *args)
{
    return PyMemoryView_FromMemory(buf, sizeof(buf), PyBUF_READ);
}

static PyObject *
ex_mview_rw_memory(PyObject *self, PyObject *args)
{
    return PyMemoryView_FromMemory(buf, sizeof(buf), PyBUF_WRITE);
}

static PyMethodDef ex_methods[] = {
    {"mview_ro_memory", ex_mview_ro_memory, METH_VARARGS, NULL},
    {"mview_rw_memory", ex_mview_rw_memory, METH_VARARGS, NULL},
    {NULL},
};

static struct PyModuleDef exmodule = {
    PyModuleDef_HEAD_INIT,
    "ex",
    NULL,
    0,
    ex_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC
PyInit_ex(void)
{
    return PyModuleDef_Init(&exmodule);
}
```
`setup.py`:
```
from setuptools import Extension, setup

setup(
    name="ex",
    ext_modules=[
        Extension(
            name="ex",
            sources=["exmodule.c"],
        ),
    ],
)
```
`test.py`:
```
import sys
import ex
print(f'{sys.version=}')
print(f'{ex.mview_ro_memory().readonly=}')
print(f'{ex.mview_rw_memory().readonly=}')
```

Output, using the `python3` and `pypy3` from Debian 12:
```
sys.version='3.11.2 (main, May  2 2024, 11:59:08) [GCC 12.2.0]'
ex.mview_ro_memory().readonly=True
ex.mview_rw_memory().readonly=False

sys.version='3.9.16 (7.3.11+dfsg-2+deb12u2, May 20 2024, 22:08:06)\n[PyPy 7.3.11 with GCC 12.2.0]'
ex.mview_ro_memory().readonly=False
ex.mview_rw_memory().readonly=True
```

**Comment by mattip** [comment]
Closed by #4993
