### ISSUE TITLE
atexit functions aren't being called (was: Unclosed multiprocessing.Manager process lives on when the main process gets interrupted)

### ISSUE THREAD

**Issue by alexprengere** [pypy/pypy#4995]
CPython and PyPy have different behavior here.
Tested on PyPy 7.3.16 (3.9) and a few earlier releases (at least until 7.3.11).

Here is a minimal reproducer:

```python
import time
from multiprocessing import Manager

manager = Manager()
time.sleep(10)  # kill me here
```

During the `sleep`, if the main process get interrupted with `SIGINT`, `SIGTERM` or `SIGQUIT`, then you can see that the child process spawned when creating the `manager` lives on. On CPython it gets killed as well (edit: its only gets killed for `SIGINT`).

Note that this issue does **not** appear if:
* a context manager is used, so the manager exits properly:
```python
with Manager() as manager:
    time.sleep(10)
```
* the main process exits normally (no interruption), then the manager process is cleanup up:
```python
manager = Manager()
# no manager.__exit__(), no sleep()
```

Comparing the finalization code between [PyPy](https://github.com/pypy/pypy/blob/branches/release-pypy3.9-v7.x/lib-python/3/multiprocessing/managers.py#L673) and [CPython](https://github.com/python/cpython/blob/main/Lib/multiprocessing/managers.py#L685
), it looks like 2 years ago some additional cleanup code was added: check the [issue](https://github.com/python/cpython/issues/91231) and [PR](https://github.com/python/cpython/pull/32112/files) (there is a discussion about the additional `kill()` in the PR):

```python
class BaseManager(object):
    ...

    @staticmethod
    def _finalize_manager(process, address, authkey, state, _Client,
                          shutdown_timeout):
       ...
            if process.is_alive():
                util.info('manager still alive')
                if hasattr(process, 'terminate'):
                    util.info('trying to `terminate()` manager process')
                    process.terminate()
                    process.join(timeout=shutdown_timeout)
                    if process.is_alive():
                        util.info('manager still alive after terminate')
                        # process.kill()  <-- only in CPython, after PR 32112
                        # process.join()  <-- only in CPython, after PR 32112
```

I am not 100% sure this is the culprit, but I could check if I get some confirmation this is going in the right direction 😉

**Comment by mattip** [comment]
I don't see that difference comparing to PyPy 3.9 v7.3.16. Are you sure you are comparing correctly?

**Comment by mattip** [comment]
Sorry, my bad. That code was not backported to CPython 3.9. Sure, give it a try, see if it fixes the problem.

**Comment by alexprengere** [comment]
Your point is interesting, I did not check older versions of CPython, and it looks like all the way up to CPython 3.6, this "bug" is **not** present. So it may not be related to PR-32112.
I will check anyway.

**Comment by alexprengere** [comment]
After compiling from sources, starting from `release-pypy3.10-v7.3.16` and adding the additional `kill` and `join`, the issue is **still** there, so I checked a bit further.

I can tell that the [`_finalize_manager`](https://github.com/pypy/pypy/blob/branches/py3.9/lib-python/3/multiprocessing/managers.py#L651) is **never** called when PyPy get a SIGINT, but it is called on CPython. Finalizers are registered using [`util.Finalize`](https://github.com/pypy/pypy/blob/branches/py3.9/lib-python/3/multiprocessing/managers.py#L563) in `multiprocessing/util.py`. There are basically no differences in the code between CPython and PyPy for `multiprocessing/util.py`.

This [`Finalize`](https://github.com/pypy/pypy/blob/branches/py3.9/lib-python/3/multiprocessing/util.py#L203) class registers the finalizers in a global [`_finalizer_registry`](https://github.com/pypy/pypy/blob/branches/py3.9/lib-python/3/multiprocessing/util.py#L178) variable, and this variable is used by a [`_exit_function`](https://github.com/pypy/pypy/blob/branches/py3.9/lib-python/3/multiprocessing/util.py#L320-L360) that is used by [`atexit`](https://github.com/pypy/pypy/blob/branches/py3.9/lib-python/3/multiprocessing/util.py#L362).

For some reason I do not understand (yet), PyPy never executes the `_exit_function` when it gets the SIGINT, though it is registered with atexit.

**Comment by alexprengere** [comment]
So it looks like this is "just" due to `atexit` not working as expected. Using this script:

```python
import time
import atexit

def callback():
    print('atexit callback')

atexit.register(callback)
time.sleep(10)  # kill me here
```
Using any CPython from 3.6 to 3.12, on WSL, and killing the script during the `time.sleep()`, `callback` **is** called.
Using pypy2.7 (7.3.16), it works as expected as well, but using pypy3.9 and pypy3.10 (7.3.16), it does not work, as `callback` is not called.

I also checked that on pypy2.7, the "manager process that lives on" issue is not there, meaning, this is very likely to be "just" an `atexit.register` issue.

**Comment by cfbolz** [comment]
wow, that is obviously really bad, thanks for hunting that down. I'll look into it.

**Comment by cfbolz** [comment]
I've written a prototype in https://github.com/pypy/pypy/commit/f3d1b3e55e4f6a5ed500bb2015fdfbb2e81ab386, need to test and merge it.

**Comment by mattip** [comment]
The py3.9-call-atexit-despite-sigint branch (with f3d1b3e) was merged.

**Comment by mattip** [comment]
There is a new buildbot failure on test_threading.py::test_fork_at_exit.

**Comment by mattip** [comment]
The buildbot failure is only on py3.9 and not on py3.10. Closing, thanks @cfbolz
