### ISSUE TITLE
cmd-module tab completion is different between pypy and cpython

### ISSUE THREAD

**Issue by cecinestpasunepipe** [pypy/pypy#5006]
Hi, it seems there is an old version of pyrepl/readline in the distros at https://pypy.org/download.html since I get an error in the cmd.py module concerning the use of xrange. After replacing readline.py with the version at https://github.com/pypy/pyrepl (https://github.com/pypy/pyrepl/blob/master/pyrepl/readline.py) everything works fine. I understand that you are currently busy replacing this version (https://github.com/pypy/pypy/issues/4990) but can you for now update the distros on the main pypy site to have the new pyrepl/readline code please? Because now it seems to be unusable. Thanks in advance. Sorry if this issue is a duplicate, I tried scanning the issues but I could not find a similar issue.

**Comment by cfbolz** [comment]
Can you please report more precisely what doesn't work with the last PyPy release? What exactly are you trying and what is breaking? What error message do you get, and what is your operating system?

**Comment by cecinestpasunepipe** [comment]
Hi, thank you for this very quick response.

Well, autocomplete does not work. To be more precise:
```

>>>> import readline
>>>> raedline.get_begidx()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'raedline' is not defined. Did you mean: 'readline'?
>>>> raedline.get_begidx()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'raedline' is not defined. Did you mean: 'readline'?
>>>> readline.get_begidx()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gabor/Downloads/pypy3.10-v7.3.16-linux64/lib/pypy3.10/pyrepl/readline.py", line 395, in get_begidx
    return self._get_idxs()[0]
  File "/home/gabor/Downloads/pypy3.10-v7.3.16-linux64/lib/pypy3.10/pyrepl/readline.py", line 388, in _get_idxs
    for i in xrange(cursor - 1, -1, -1):
NameError: name 'xrange' is not defined. Did you mean: 'range'?

```

Version info:

```
Python 3.10.14 (75b3de9d9035, Apr 21 2024, 10:54:48)
[PyPy 7.3.16 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>> import platform
>>>> platform.python_implementation()
'PyPy'

```

I downloaded the latest version from: https://pypy.org/download.html

**Comment by cecinestpasunepipe** [comment]
get_begidx() is used by cmd.py to implement autocomplete.

**Comment by cfbolz** [comment]
the specific problem that you reported isn't there on the release branch. can try a nightly build to see whether your larger program works: https://buildbot.pypy.org/nightly/py3.10/

**Comment by cecinestpasunepipe** [comment]
I can confirm that latest build does not have this specific error. However autocomplete still seems broken:

Test

```
import cmd

class Console(cmd.Cmd):

    def completedefault(self, text: str, line: str, begidx: int, endidx: int):
        return ["foo", "bar"]

if __name__ == "__main__":
    Console().cmdloop()
    
```

CPython:

```
 python3 ~/cmdtest.py 
(Cmd) cmd 
bar  foo  
```


PyPy latest build:

`(Cmd) cmd <tab> <tab>			`

**Comment by cfbolz** [comment]
ok, I'll check it out in more details a the next couple of days

**Comment by cecinestpasunepipe** [comment]
Great, thank you, will do.

**Comment by cecinestpasunepipe** [comment]
Unfortunately the latest version still does have some issues. Using my test file above see the difference:

CPython:

```
(Cmd) cmd <tab>
bar  foo  
```

PyPy latest:

`(Cmd) cmd <tab>help`

Given the code in my test sample I would expect `bar foo` upon pressing `tab` after the space. However PyPy only gives me the default `help` command instead. For some reason,` completedefault()` is not getting called?

**Comment by cfbolz** [comment]
yes, can confirm, thanks for trying it again! I'm looking now.

**Comment by cfbolz** [comment]
oh, btw: isn't the `cmd` behaviour also broken on cpython? In your example, if I do this:

```
(Cmd) cmd f<tab>
```

it should complete `foo`, no? but for me it doesn't, neither on CPython nor on pypy.

**Comment by cfbolz** [comment]
@cecinestpasunepipe I think this is fixed now, I'm closing it, please re-open if it still doesn't work for you.

**Comment by cfbolz** [comment]
@cecinestpasunepipe yeah, it's normal, and CPython 3.13 will also have the message.

**Comment by cecinestpasunepipe** [comment]
Ok, great, then I consider it fixed. Thanks for your help. Much appreciated!
