### ISSUE TITLE
W_TextIOWrapper.tell_w/seek_w is very slow sometimes

### ISSUE THREAD

**Issue by cfbolz** [pypy/pypy#5009]
from here: https://github.com/fox-it/dissect.target/issues/243

the following program is *much* slower on pypy 3.10 than on cpython 3.11:

```python
from __future__ import annotations

from typing import TextIO
import io

def reverse_readlines(fh: TextIO, chunk_size: int = 1024 * 1024 * 8) -> Iterator[str]:
    """Like iterating over a ``TextIO`` file-like object, but starting from the end of the file.

    Args:
        fh: The file-like object (opened in text mode) to iterate lines from.
        chunk_size: The chunk size to use for iterating over lines.

    Returns:
        An iterator of lines from the file-like object, in reverse.
    """
    offset = fh.seek(0, io.SEEK_END) & ((1 << 64) - 1)
    lines = []

    prev_offset = offset
    while offset > 0:
        if offset < chunk_size:
            chunk_size = offset
        offset -= chunk_size
        fh.seek(offset)

        lines = _rev_readlines_helper(fh, chunk_size, prev_offset)

        yield from reversed(lines[1:])

        if prev_offset == offset:
            # Previous lines are unreadable due to decoding errors
            raise UnicodeDecodeError(fh.encoding, b"", 0, offset + 1, "failed to decode line")

        prev_offset = offset

    if lines:
        yield lines[0]

def _rev_readlines_helper(fh, chunk_size, prev_offset):
    lines = []
    # tell() on TextIO returns a cookie which includes encode/decoder state
    # Lower 64 bit are the file position
    # https://peps.python.org/pep-3116/#text-i-o
    # See TextIOWrapper._pack_cookie in _pyio.py for more detail
    while (fh.tell() & ((1 << 64) - 1)) < prev_offset:
        try:
            lines.append(fh.readline())
        except UnicodeDecodeError:
            offset += 1
            fh.seek(offset)
    return lines

def main():
    for i in range(1000):
        with open(__file__, "rt") as fh:
            result = []
            for line in reverse_readlines(fh):
                result.append(line)

main()
```

**Comment by mattip** [comment]
There is a _lot_ of code in [`tell_w`](https://github.com/pypy/pypy/blob/bbe2fa06e6aeb459737100df55608b2b6dedd150/pypy/module/_io/interp_textio.py#L1271) (assuming that is the correct one). It seems to match [cpython's implemantation](https://github.com/python/cpython/blob/ec89620e5e147ba028a46dd695ef073a72000b84/Modules/_io/textio.c#L2713), and looking at the git blame I don't see any real changes in the past ~5 years.

**Comment by cfbolz** [comment]
On my laptop PyPy is 150x slower. We should definitely do something about that. It's a post-release task though

**Comment by mattip** [comment]
I think we are missing the shortcut on [lines 2769 - 2802](https://github.com/python/cpython/blob/31302f5fc24eecd693f0c8aaba7c2840b09b594d/Modules/_io/textio.c#L2769-L2802). The CPython code never goes past it to the big `while` loop, it always returns at line 2808 (or before, at [line 2719](https://github.com/python/cpython/blob/31302f5fc24eecd693f0c8aaba7c2840b09b594d/Modules/_io/textio.c#L2719).

**Comment by mattip** [comment]
Also see #3126 which might be tangentially related.

**Comment by mattip** [comment]
FWIW, CPython3.10 is much slower than CPython3.11. I added the missing optimization to the latest py3.10 HEAD. Now when I run `time <python> <script>` I get
version |  time
---|--
PyPy3.10 HEAD | 1000 | 0.325s
CPython3.10 | 1000 | 0.176s
CPython3.11 | 1000 | 0.176s

There is still another place where CPython uses `b2cratio` which I added in this change, maybe that gives a little more speedup

**Comment by cfbolz** [comment]
the cpy 3.10 numbers still look wrong?

**Comment by mattip** [comment]
Maybe. When I rerun it I get CPython3.10 0.183 and CPython3.11 0.179.

**Comment by mattip** [comment]
Closing
