### ISSUE TITLE
PyPyImport_ImportModuleLevel symbol undefined?

### ISSUE THREAD

**Issue by rtobar** [pypy/pypy#5013]
```
$> uname -a
Linux myhost 6.8.0-41-generic #41-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug  2 20:41:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

$> python -VV
Python 3.9.18 (7.3.15+dfsg-1build3, Apr 01 2024, 03:12:48)
[PyPy 7.3.15 with GCC 13.2.0]
```

Also seen with `pypy3.9-v7.3.16-macos_x86_64` [here](https://github.com/ICRAR/ijson/actions/runs/10626144823/job/29457248738#step:4:9000), so probably affects multiple versions.

Errors occur when compiling a C extension that uses the `PyImport_ImportModuleLevel` C API. When compiling with clang one gets a comiple-time error like in the link above, which I can also reproduce locally:

```
$> CC=clang python -mbuild -w
....
clang -DNDEBUG -O2 -fPIC -Isrc/ijson/backends/ext/_yajl2 -I/tmp/build-env-13pnm7x2/include -I/usr/include/pypy3.9 -c src/ijson/backends/ext/_yajl2/module.c -o build/temp.linux-x86_64-pypy39/src/ijson/backends/ext/_yajl2/module.o
src/ijson/backends/ext/_yajl2/module.c:80:21: error: call to undeclared function 'PyPyImport_ImportModuleLevel'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   80 |         PyObject *module = PyImport_ImportModuleLevel(
      |                            ^
/usr/include/pypy3.9/pypy_macros.h:73:36: note: expanded from macro 'PyImport_ImportModuleLevel'
   73 | #define PyImport_ImportModuleLevel PyPyImport_ImportModuleLevel
      |                                    ^
src/ijson/backends/ext/_yajl2/module.c:80:21: note: did you mean 'PyPyImport_ImportModule'?
/usr/include/pypy3.9/pypy_macros.h:73:36: note: expanded from macro 'PyImport_ImportModuleLevel'
   73 | #define PyImport_ImportModuleLevel PyPyImport_ImportModuleLevel
      |                                    ^
/usr/include/pypy3.9/pypy_decl.h:376:30: note: 'PyPyImport_ImportModule' declared here
  376 | PyAPI_FUNC(struct _object *) PyImport_ImportModule(const char *arg0);
      |                              ^
/usr/include/pypy3.9/pypy_decl.h:375:31: note: expanded from macro 'PyImport_ImportModule'
  375 | #define PyImport_ImportModule PyPyImport_ImportModule
      |                               ^
src/ijson/backends/ext/_yajl2/module.c:80:12: error: incompatible integer to pointer conversion initializing 'PyObject *' (aka 'struct _object *') with an expression of type 'int' [-Wint-conversion]
   80 |         PyObject *module = PyImport_ImportModuleLevel(
      |                   ^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~
   81 |             MODULE_NAME, PyEval_GetGlobals(), Py_None, NULL, 1
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   82 |         );
      |         ~
2 errors generated.
```

When compiling with gcc these are warnings only, but the resulting extension shared library cannot be loaded:

```python
>>>> import ijson
>>>> ijson.get_backend('yajl2_c')
Traceback (most recent call last):
...
ImportError: .../_yajl2.pypy39-pp73-x86_64-linux-gnu.so: undefined symbol: PyPyImport_ImportModuleLevel
>>>> 
```

I am confused because I can see the function defined in the PyPy source code, but maybe there's some hook that is missing to make it available via `cpyext`? I did contribute some time ago to PyPy (async-related fixes for C extensions), so I might be able to take a look if given some minor guidance.

**Comment by rtobar** [comment]
This actually seems similar to https://github.com/pypy/pypy/issues/3532, where the missing symbol was already reported, alongside other two. The fix in 34aa8aa180 added two of them, since the `PyImport_ImportModuleLevel` seems to already have been in `import.h`. However `import.h` isn't part of `Python.h`. Is that the actual problem? If that's the case, I'm curious to learn how the function being declared in the header determines whether the symbol is given the correct visibility in the shared library.

**Comment by cfbolz** [comment]
I think that the ` PyAPI_FUNC(struct _object *)` declaration expands to the correct `extern` annotation. I think it's in [pyport.h](https://github.com/pypy/pypy/blob/branches/py3.10/pypy/module/cpyext/include/pyport.h), but it's in a mass of ifdefs.

does the problem go away if you include `import.h` in your `.c` file?

**Comment by rtobar** [comment]
I was thinking the same thing, but ran out of time to try. I'll give it a shot and report back. I also wanted to check the symbols in the shared library.

**Comment by mattip** [comment]
I added the missing include in dc81fc45b53. This is for python3.10, we don't support python3.9 anymore. You probably want to drop it from [ijson](https://github.com/ICRAR/ijson/blob/8be4895c276601ae998d8f3927033e3d447cdef2/.github/workflows/fast-built-and-test.yml#L22)

**Comment by rtobar** [comment]
Thanks @mattip, much appreciated, and thanks for the job about 3.9 not being supported anymore, I'll drop that too. I can also easily workaround this issue until a new PyPy is released.

BTW, I tried locally to add the include for `import.h` and indeed it now compiles, but the library still fails to load due to the missing symbol (where would I find the symbol defined in a PyPy installation?). Does this mean I need to build/translate PyPy locally to check this is working as expected?

**Comment by mattip** [comment]
Hmm. That shouldn't happen, I see the symbol redefined and exported, even in a PyPy that did not have the `#include <import.h>`. Did you use the PyPy-specific include path to get the redefine?
```
$ grep PyPyImport_ImportModuleLevel <path>/pypy3.10-v7.3.16-linux64/include/pypy3.10/*.h
<path>/pypy3.10-v7.3.16-linux64/include/pypy3.10/pypy_decl.h:#define PyImport_ImportModuleLevelObject PyPyImport_ImportModuleLevelObject
<path>/pypy3.10-v7.3.16-linux64/include/pypy3.10/pypy_macros.h:#define PyImport_ImportModuleLevel PyPyImport_ImportModuleLevel
```
```
$ objdump -x <path>/pypy3.10-v7.3.16-linux64/bin/libpypy3.10-c.so | grep PyPyImport_ImportModuleLevel
00000000023a21d0 l     F .text  0000000000000077 PyPyImport_ImportModuleLevel
00000000018a3370 g     F .text  000000000000001f PyPyImport_ImportModuleLevelObject
```

**Comment by rtobar** [comment]
No, I hadn't `#include`d with the full path before, but I did now and had the same effect; namely, the extension compiles successfully but it fails to load.

To answer one of your questions, the `pypy_macros.h` file defines the alias correctly (you'll see it in the original error message in this issue), but the name it aliased to wasn't defined because of the missing `import.h` include, hence the compilation error.

I'm not sure how my PyPy gets compiled. I'm using the stock PyPy from Ubuntu 24.04 and don't see *any* local symbols defined in `libpypy3.9-c.so`, which I also found strange -- hence me asking where should I find them. They're not in the `pypy3.9` binary either.

```
$> objdump -t /usr/lib/x86_64-linux-gnu/libpypy3.9-c.so

/usr/lib/x86_64-linux-gnu/libpypy3.9-c.so:     file format elf64-x86-64

SYMBOL TABLE:
no symbols


$> objdump -t /usr/bin/pypy3.9 

/usr/bin/pypy3.9:     file format elf64-x86-64

SYMBOL TABLE:
no symbols
```

But if I request dynamic symbols as well then I get:

```
$> objdump -t -T /usr/lib/x86_64-linux-gnu/libpypy3.9-c.so | grep ImportModule
000000000195cfa0 g    DF .text  000000000000001a  Base        PyPyImport_ImportModuleNoBlock
0000000001999040 g    DF .text  0000000000001042  Base        PyPyImport_ImportModuleLevelObject
0000000001996650 g    DF .text  000000000000001a  Base        PyPyImport_ImportModule
```

So `PyPyImport_ImportModuleLevel` is indeed missing and hence the shared lib fails to load.

I know you said that 3.9 was not supported anymore, but this seems to be a function that was added a long time ago both to CPython and PyPy, hence my surprise to not see it working.

I also just downloaded [the latest ](https://downloads.python.org/pypy/pypy3.10-v7.3.17-linux64.tar.bz2) PyPy 3.10 (7.3.17) binary for Linux x64 and I get the same issue (compilation warning/error and not able to load the extension). It again boils down to the missing include and to the missing symbol:

```
$> objdump -t -T ~/downloads/pypy3.10-v7.3.17-linux64/bin/libpypy3.10-c.so | grep ImportModule
00000000018bbba0 g    DF .text  0000000000000016  Base        PyPyImport_ImportModule
00000000018bc4a0 g    DF .text  000000000000001f  Base        PyPyImport_ImportModuleLevelObject
00000000018bbbc0 g    DF .text  0000000000000016  Base        PyPyImport_ImportModuleNoBlock
```

**Comment by rtobar** [comment]
(and for what is worth, the latest [nightly build](https://buildbot.pypy.org/nightly/py3.10/pypy-c-jit-185209-55a4184446f6-linux64.tar.bz2) also misses the symbol)

**Comment by mattip** [comment]
Huh. Maybe the `include <import.h>` _is_ important to get the correct `Py_API_FUNC` declaration
```
PyAPI_FUNC(PyObject *) PyImport_ImportModuleLevel(...
```

so a build that includes https://github.com/pypy/pypy/commit/dc81fc45b53c736dda85ffefe70c273d5f2ab9e3 will now properly export it from the shared object.

**Comment by rtobar** [comment]
Thanks @mattip, I'll wait for the nightly build to pop up and test again to verify

**Comment by rtobar** [comment]
@mattip I can confirm that the [latest nightly build](https://buildbot.pypy.org/nightly/py3.10/pypy-c-jit-185219-9c56162c60a6-linux64.tar.bz2) containing your fix now has the definition after including `Python.h`, the symbol is in the shared library, and my extension now compiles and loads as expected. Here's the symbol situation, for completeness:

```
$> for f in `find ~/downloads/pypy-c-jit-185219-9c56162c60a6-linux64/ -type f`; do objdump -t -T $f 2> /dev/null | grep 'ImportModuleLevel\>' && echo $f; done
00000000023d5250 g     F .text  0000000000000077 PyPyImport_ImportModuleLevel
/home/rtobar/downloads/pypy-c-jit-185219-9c56162c60a6-linux64/bin/libpypy3.10-c.so.debug
00000000023d5250 g    DF .text  0000000000000077  Base        PyPyImport_ImportModuleLevel
/home/rtobar/downloads/pypy-c-jit-185219-9c56162c60a6-linux64/bin/libpypy3.10-c.so
$> 
```

Many thanks again for the fix!
