### ISSUE TITLE
Program's Recursive Call Causes Terminal to Hang Indefinitely

### ISSUE THREAD

**Issue by zzl261004** [pypy/pypy#5021]
When running a simple Python script with the `--jit function_threshold=1` option, the terminal hangs indefinitely without producing any output. This issue does not occur when running the script with the default JIT settings or with the JIT turned off.

1. program.py

```python
class RecursionTest:
    def test_recursive_call(self):
        
        class CustomClass:
            pass
        CustomClass.__call__ = CustomClass()
        instance = CustomClass()

        try:
            instance()  
        except RecursionError:
            print("RecursionError caught as expected.")
        else:
            raise AssertionError("Failed to raise RecursionError")

if __name__ == '__main__':
    test_instance = RecursionTest()
    test_instance.test_recursive_call()
    print("test_recursive_call passed.")
```
2. Run the following commands in the terminal:
```bash
pypy program.py
pypy --jit off program.py
```
   In both cases, the output is as expected:
```bash
RecursionError caught as expected.
test_recursive_call passed.
```
3. run the program with the function_threshold=1 JIT option:
```bash
pypy --jit function_threshold=1 program.py
```
**The terminal hangs indefinitely without any output.**

Environment:
Python 3.9.19 (a2113ea87262, Apr 21 2024, 05:40:24)
[PyPy 7.3.16 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
Operating System: Ubuntu 22.04.4 LTS

**Comment by cfbolz** [comment]
can reproduce, interesting bug! maybe related to tail-call-optimization in the JIT.

**Comment by cfbolz** [comment]
the linked commit fixes it, let's check in the nightly build tomorrow.

**Comment by zzl261004** [comment]
Thank you very much, this issue has been resolved. I will now close this issue.
