### ISSUE TITLE
Terminal Hangs or Process Blocks in PyPy with Multiprocessing Queue (Works Fine on CPython 3.13)

### ISSUE THREAD

**Issue by zzl261004** [pypy/pypy#5025]
I have encountered an issue where my Python script causes the terminal to hang or become blocked when running on PyPy, regardless of whether JIT is enabled or disabled. However, this issue does not occur when I run the same script on CPython 3.13.

The issue can be reproduced by running the following code using PyPy, **both with JIT and with --jit off:**

```python
import time
from multiprocessing import Process, Queue, current_process

def worker(input, output):
    for func, args in iter(input.get, 'STOP'):
        result = func(*args)
        output.put(result)

def mul(a, b):
    time.sleep(0.02)
    return a * b

def test():
    task_queue = Queue()
    done_queue = Queue()

    tasks = [(mul, (i, 7)) for i in range(10)]

    for task in tasks:
        task_queue.put(task)

    processes = []
    for _ in range(2):  
        p = Process(target=worker, args=(task_queue, done_queue))
        processes.append(p)
        p.start()

    for _ in range(len(tasks)):
        print(done_queue.get())

    for _ in range(2):
        task_queue.put('STOP')

    for p in processes:
        p.join()


if __name__ == '__main__':
#Since the blocking doesn't occur every time, loop the test() function 100 times to reproduce the bug.
    for _ in range(100):
        test()
        print("---------------------")
```

Please note that if you run test() only once, the terminal hang or blocking might not occur. To reliably reproduce the issue, kindly loop the test() function 100 times.

Environment:
Python 3.9.19 (a2113ea87262, Apr 21 2024, 05:40:24)
[PyPy 7.3.16 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
Operating System: Ubuntu 22.04.4 LTS

**Comment by mattip** [comment]
Maybe connected with a0878f5? Can you either apply that change or try with the newer pypy3.10-v7.3.17?

**Comment by mattip** [comment]
Cool. Closing.
