### ISSUE TITLE
Invalid format(1000000000001j), returns '1e+12j'

### ISSUE THREAD

**Issue by skirpichev** [pypy/pypy#5028]
c.f. CPython:
```pycon
Python 3.13.0rc1+ (heads/3.13:bd29ce8509, Aug 29 2024, 15:30:15) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> format(1000000000001j)
'1000000000001j'
```

I would guess that pypy here uses 'g' format instead (where real zero not included in output):
```pycon
>>> format(1000000000001j, 'g')
'0+1e+12j'
```

**Comment by cfbolz** [comment]
actually the `__str__` of complex is wrong.

cpython:
```python
>>> str(1000000000001j)
'1000000000001j'
```
pypy:
```python
>>>> str(1000000000001j)
'1e+12j'

```

**Comment by skirpichev** [comment]
"is wrong too".  IIUC, in this case format() output should match str().  (I'm trying to document that in https://github.com/python/cpython/pull/122848.)

**Comment by cfbolz** [comment]
in your simplest case `format()` directly *calls* `str`, so fixing the latter fixes the format too.

(but actually there are other buggy cases in format).

**Comment by cfbolz** [comment]
should be fixed in the above commit. thanks for the bug report!

**Comment by skirpichev** [comment]
This is still valid for 3.9.

**Comment by cfbolz** [comment]
Yeah, but there won't be another 3.9 release.
