### ISSUE TITLE
Segmentation fault when calling __setstate__ on reversed() iterator in PyPy

### ISSUE THREAD

**Issue by zzl261004** [pypy/pypy#5029]
I encountered a segmentation fault while running a simple program in PyPy that works fine in CPython. Below is a minimal example to reproduce the issue:
```python
reverse_iter = reversed((5,4,3,2,1))
for item in reverse_iter:
    pass
reverse_iter.__setstate__(1)
print(list(reverse_iter)) #print [] in Cpython
```
Running the program in pypy :
```
Segmentation fault (core dumped)
```
Running the program in Cpython:
```
[]
```
Environment:
Python 3.10.14 (39dc8d3c85a7, Aug 27 2024, 14:32:27)
[PyPy 7.3.17 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
Operating System: Ubuntu 22.04.4 LTS

**Comment by cfbolz** [comment]
Thanks. Fixed in the above commit.
