### ISSUE TITLE
3.11: changes to the math module

### ISSUE THREAD

**Issue by cfbolz** [pypy/pypy#5035]
a bunch of changes in the `math` module:
- [x] [math.exp2()](https://docs.python.org/3/library/math.html#math.exp2): return 2 raised to the power of x.
- [x] [math.cbrt()](https://docs.python.org/3/library/math.html#math.cbrt): return the cube root of x.
- [x] "The behaviour of two [math.pow()](https://docs.python.org/3/library/math.html#math.pow) corner cases was changed, for consistency with the IEEE 754 specification. The operations math.pow(0.0, -math.inf) and math.pow(-0.0, -math.inf) now return inf. Previously they raised [ValueError](https://docs.python.org/3/library/exceptions.html#ValueError). (Contributed by Mark Dickinson in [bpo-44339](https://bugs.python.org/issue?@action=redirect&bpo=44339).)"
- [x] "The [math.nan](https://docs.python.org/3/library/math.html#math.nan) value is now always available. (Contributed by Victor Stinner in [bpo-46917](https://bugs.python.org/issue?@action=redirect&bpo=46917).)"
- [ ] "functions [comb()](https://docs.python.org/3/library/math.html#math.comb) and [perm()](https://docs.python.org/3/library/math.html#math.perm) are now ≈10 times faster for large arguments (with a larger speedup for larger k). (Contributed by Serhiy Storchaka in [bpo-37295](https://bugs.python.org/issue?@action=redirect&bpo=37295).)"

**Comment by cfbolz** [comment]
we always had `math.nan` unconditionally, so that is done.

**Comment by cfbolz** [comment]
`test_math` from the stdlib now passes. the `comb` and `perf` improvements are "only" an optimization, so feature-wise we are set for the math module.

**Comment by mattip** [comment]
Done, closing.
