### ISSUE TITLE
3.11: sqlite3 changes

### ISSUE THREAD

**Issue by cfbolz** [pypy/pypy#5038]
- [x] You can now disable the authorizer by passing [None](https://docs.python.org/3/library/constants.html#None) to [set_authorizer()](https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection.set_authorizer). (Contributed by Erlend E. Aasland in [bpo-44491](https://bugs.python.org/issue?@action=redirect&bpo=44491).)
- [x] Collation name [create_collation()](https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection.create_collation) can now contain any Unicode character. Collation names with invalid characters now raise [UnicodeEncodeError](https://docs.python.org/3/library/exceptions.html#UnicodeEncodeError) instead of [sqlite3.ProgrammingError](https://docs.python.org/3/library/sqlite3.html#sqlite3.ProgrammingError). (Contributed by Erlend E. Aasland in [bpo-44688](https://bugs.python.org/issue?@action=redirect&bpo=44688).)
- [x] [sqlite3](https://docs.python.org/3/library/sqlite3.html#module-sqlite3) exceptions now include the SQLite extended error code as [sqlite_errorcode](https://docs.python.org/3/library/sqlite3.html#sqlite3.Error.sqlite_errorcode) and the SQLite error name as [sqlite_errorname](https://docs.python.org/3/library/sqlite3.html#sqlite3.Error.sqlite_errorname). (Contributed by Aviv Palivoda, Daniel Shahaf, and Erlend E. Aasland in [bpo-16379](https://bugs.python.org/issue?@action=redirect&bpo=16379) and [bpo-24139](https://bugs.python.org/issue?@action=redirect&bpo=24139).)
- [x] Add [setlimit()](https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection.setlimit) and [getlimit()](https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection.getlimit) to [sqlite3.Connection](https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection) for setting and getting SQLite limits by connection basis. (Contributed by Erlend E. Aasland in [bpo-45243](https://bugs.python.org/issue?@action=redirect&bpo=45243).)
- [x] [sqlite3](https://docs.python.org/3/library/sqlite3.html#module-sqlite3) now sets [sqlite3.threadsafety](https://docs.python.org/3/library/sqlite3.html#sqlite3.threadsafety) based on the default threading mode the underlying SQLite library has been compiled with. (Contributed by Erlend E. Aasland in [bpo-45613](https://bugs.python.org/issue?@action=redirect&bpo=45613).)
- [x] [sqlite3](https://docs.python.org/3/library/sqlite3.html#module-sqlite3) C callbacks now use unraisable exceptions if callback tracebacks are enabled. Users can now register an [unraisable hook handler](https://docs.python.org/3/library/sys.html#sys.unraisablehook) to improve their debug experience. (Contributed by Erlend E. Aasland in [bpo-45828](https://bugs.python.org/issue?@action=redirect&bpo=45828).)
- [x] Fetch across rollback no longer raises [InterfaceError](https://docs.python.org/3/library/sqlite3.html#sqlite3.InterfaceError). Instead we leave it to the SQLite library to handle these cases. (Contributed by Erlend E. Aasland in [bpo-44092](https://bugs.python.org/issue?@action=redirect&bpo=44092).)
- [x] Add [serialize()](https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection.serialize) and [deserialize()](https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection.deserialize) to [sqlite3.Connection](https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection) for serializing and deserializing databases. (Contributed by Erlend E. Aasland in [bpo-41930](https://bugs.python.org/issue?@action=redirect&bpo=41930).)
- [x] Add [create_window_function()](https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection.create_window_function) to [sqlite3.Connection](https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection) for creating aggregate window functions. (Contributed by Erlend E. Aasland in [bpo-34916](https://bugs.python.org/issue?@action=redirect&bpo=34916).)
- [x] Add [blobopen()](https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection.blobopen) to [sqlite3.Connection](https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection). [sqlite3.Blob](https://docs.python.org/3/library/sqlite3.html#sqlite3.Blob) allows incremental I/O operations on blobs. (Contributed by Aviv Palivoda and Erlend E. Aasland in [bpo-24905](https://bugs.python.org/issue?@action=redirect&bpo=24905).)

**Comment by mattip** [comment]
Done, closing
