### ISSUE TITLE
3.11: exception groups

### ISSUE THREAD

**Issue by cfbolz** [pypy/pypy#5040]
a lot of it is already implemented in the `py3.11-old-stdlib` branch, but some of the bytecode compiler support is still missing.

**Comment by cfbolz** [comment]
work is happening here: https://github.com/nirit100/pypy/tree/branches/py3.11-except-groups-impl

**Comment by cfbolz** [comment]
I've just merged this to py3.11-old-stdlib. The basic features of exception groups seem to work.

**Comment by mattip** [comment]
Is this done?

**Comment by cfbolz** [comment]
nope, there are a lot of test failures still :-(

**Comment by cfbolz** [comment]
I'm closing this, I think it should be mostly correct now
