### ISSUE TITLE
3.11: object.__getstate__

### ISSUE THREAD

**Issue by cfbolz** [pypy/pypy#5044]
"Added [`object.__getstate__()`](https://docs.python.org/3/library/pickle.html#object.__getstate__), which provides the default implementation of the `__getstate__()` method. [copy](https://docs.python.org/3/library/copy.html#module-copy)ing and [pickle](https://docs.python.org/3/library/pickle.html#module-pickle)ing instances of subclasses of builtin types [bytearray](https://docs.python.org/3/library/stdtypes.html#bytearray), [set](https://docs.python.org/3/library/stdtypes.html#set), [frozenset](https://docs.python.org/3/library/stdtypes.html#frozenset), [collections.OrderedDict](https://docs.python.org/3/library/collections.html#collections.OrderedDict), [collections.deque](https://docs.python.org/3/library/collections.html#collections.deque), [weakref.WeakSet](https://docs.python.org/3/library/weakref.html#weakref.WeakSet), and [datetime.tzinfo](https://docs.python.org/3/library/datetime.html#datetime.tzinfo) now copies and pickles instance attributes implemented as [slots](https://docs.python.org/3/glossary.html#term-__slots__). This change has an unintended side effect: It trips up a small minority of existing Python projects not expecting [`object.__getstate__()`](https://docs.python.org/3/library/pickle.html#object.__getstate__) to exist. See the later comments on [gh-70766](https://github.com/python/cpython/issues/70766) for discussions of what workarounds such code may need. (Contributed by Serhiy Storchaka in [bpo-26579](https://bugs.python.org/issue?@action=redirect&bpo=26579).)"

**Comment by mattip** [comment]
I did a rough first part of this: adding the function and having it return `obj.__dict__` if one exists. I still need to do the part about adding `__slots__` which then returns `(dict, slots)`

**Comment by mattip** [comment]
Should be done now, barring new bugs

**Comment by mattip** [comment]
Fixed in 7f74d7e1bcf
