### ISSUE TITLE
3.11: deprecate `__trunc__` when calling `int()`

### ISSUE THREAD

**Issue by cfbolz** [pypy/pypy#5055]
"The delegation of [int()](https://docs.python.org/3/library/functions.html#int) to [__trunc__()](https://docs.python.org/3/reference/datamodel.html#object.__trunc__) is now deprecated. Calling int(a) when type(a) implements __trunc__() but not [__int__()](https://docs.python.org/3/reference/datamodel.html#object.__int__) or [__index__()](https://docs.python.org/3/reference/datamodel.html#object.__index__) now raises a [DeprecationWarning](https://docs.python.org/3/library/exceptions.html#DeprecationWarning). (Contributed by Zackery Spytz in [bpo-44977](https://bugs.python.org/issue?@action=redirect&bpo=44977).)"

**Comment by shimst3r** [comment]
I'll take this. :)

**Comment by shimst3r** [comment]
Just to clarify:

https://github.com/pypy/pypy/blob/5b053edfbd96ec039361452b088fcc98376977e4/pypy/objspace/std/intobject.py#L737-L741

This is the section that needs to raise the deprecation warning, am I correct? Plus all the occurrences of tests similar to

https://github.com/pypy/pypy/blob/5b053edfbd96ec039361452b088fcc98376977e4/pypy/objspace/std/test/test_intobject.py#L574-L581

where the object under test is derived from a class that only implements `__trunc__`?

**Comment by mattip** [comment]
Done in 6586ba8d9
