### ISSUE TITLE
matplotlib tkagg issues

### ISSUE THREAD

**Issue by gborrageiro** [pypy/pypy#5064]
My server is `Rocky Linux release 9.4 (Blue Onyx)`.
I am running pypy version:
```
Python 3.10.14 (39dc8d3c85a7, Aug 27 2024, 14:32:27)
[PyPy 7.3.17 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)]
```
My matplotlib version is `3.9.2`.

Creating plots is proving problematic:
```
import matplotlib.pyplot as plt

plt.switch_backend("tkagg")
fig, ax = plt.subplots()
```

```
Traceback (most recent call last):
  File "/home/gabrielborrageiro/Projects/analytics/scratch.py", line 4, in <module>
    fig, ax = plt.subplots()
              ^^^^^^^^^^^^^^
  File "/home/gabrielborrageiro/env/analytics/lib/pypy3.10/site-packages/matplotlib/pyplot.py", line 1759, in subplots
    fig = figure(**fig_kw)
          ^^^^^^^^^^^^^^^^
  File "/home/gabrielborrageiro/env/analytics/lib/pypy3.10/site-packages/matplotlib/pyplot.py", line 1027, in figure
    manager = new_figure_manager(
  File "/home/gabrielborrageiro/env/analytics/lib/pypy3.10/site-packages/matplotlib/pyplot.py", line 550, in new_figure_manager
    return _get_backend_mod().new_figure_manager(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gabrielborrageiro/env/analytics/lib/pypy3.10/site-packages/matplotlib/backend_bases.py", line 3507, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gabrielborrageiro/env/analytics/lib/pypy3.10/site-packages/matplotlib/backend_bases.py", line 3512, in new_figure_manager_given_figure
    return cls.FigureCanvas.new_manager(figure, num)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gabrielborrageiro/env/analytics/lib/pypy3.10/site-packages/matplotlib/backend_bases.py", line 1797, in new_manager
    return cls.manager_class.create_with_canvas(cls, figure, num)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gabrielborrageiro/env/analytics/lib/pypy3.10/site-packages/matplotlib/backends/_backend_tk.py", line 483, in create_with_canvas
    window = tk.Tk(className="matplotlib")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/pypy3/lib/pypy3.10/tkinter/__init__.py", line 2306, in __init__
    self._loadtk()
  File "/usr/local/pypy3/lib/pypy3.10/tkinter/__init__.py", line 2322, in _loadtk
    raise RuntimeError("tk.h version (%s) doesn't match libtk.a version (%s)"
RuntimeError: tk.h version (8.6) doesn't match libtk.a version (8.5)
```

The default tcl/tk on Rocky is 8.6 and I have compiled 8.5 versions, updated `LD_LIBRARY_PATH` and `PATH` to reflect this; I still get the same error as above. I tried `PyQT5` and `PyQT6` and that is presenting even greater challenges.
Any help would be greatly appreciated.

**Comment by mattip** [comment]
Our packages are built with a portable pypy that bundles tkinter. If you want to relink it with a different tk, you need to rebuild the cffi-based extension module by rerunnnig [tk_build.py](https://github.com/pypy/pypy/blob/py3.10/lib_pypy/_tkinter/tklib_build.py) which should be in the _tkinter directory.

**Comment by mattip** [comment]
I tried to reproduce:
```
$ ../pypy3.10-v7.3.17-linux64/bin/pypy -m venv /tmp/venv310pypy
$ source /tmp/venv310pypy/bin/activate
(venv310pypy) $ python
Python 3.10.14 (39dc8d3c85a7, Aug 27 2024, 14:32:27)
[PyPy 7.3.17 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
$ python -c "import tkinter as tk; tk.Tk()"
...
_tkinter.TclError: Can't find a usable init.tcl in the following directories: 
    /usr/share/tcl8.5 /tmp/venv310pypy/lib/tcl8.5 /tmp/lib/tcl8.5 /tmp/venv310pypy/library /tmp/library /tmp/tcl8.5.13/library /tcl8.5.13/library
```

So it seems a venv created from the portable builds is not correctly mangling the search path for `init.tcl`. This is related to #5096

**Comment by mattip** [comment]
maybe fixed in ecf59b835ee, let's see how the nightly builds go.

**Comment by mattip** [comment]
The github action we run on the repo uses a docker image that is kind of messed up. You can see the package script finds [`/lib/x86_64-linux-gnu/libtcl8.6`](https://github.com/pypy/pypy/actions/runs/11879415499/job/33101301569#step:7:73) but takes the scripts from [`/usr/share/miniconda/pkgs/tk-8.6.14-h39e8969_0/lib/tcl8.6`](https://github.com/pypy/pypy/actions/runs/11879415499/job/33101301569#step:7:95), which is a different version. We will have to wait for the nightly builds on the buildbots to see that the environment is consistent. On all the linux builds we use a docker file with a controlled environment. I wonder what will happen on macOS, which uses homebrew. Hopefully it will not get confused like the github action builds.

**Comment by mattip** [comment]
The orignal report now works cleanly for me with a portable pypy and the latest 3.10 HEAD
```
pypy -c 'import matplotlib.pyplot as plt; plt.switch_backend("tkagg"); fig, ax = plt.subplots()'
```

**Comment by mattip** [comment]
Thanks for the report. Closing. Please open a new issue if the problems reappear.
