### ISSUE TITLE
Shipping completely broken. Can't pass in any arguments into the pypy command

### ISSUE THREAD

**Issue by cybergazer** [pypy/pypy#5065]
Pypy can't be passed in any arguments as of Oct 4, 2024. If you try to run "pypy myapp.py" it will not work. "pypy --version" won't work. None of these work where as they work fine in cpython

```
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

## Steps followed
Using the latest binary of pypy as specified here: https://pypy.org/download.html
Basically extracted the binaries and ran the files in the interpreter. I've tried in bash and zsh with stock config so it's not a shell issue. This seems to be a coding error on the compiled binaries of pypy.

**Comment by mattip** [comment]
Which version did you download, what is the error ( preferably copy paste the shell commands you used)?

**Comment by mattip** [comment]
Ping @cybergazer. Can you supply more information?

**Comment by mattip** [comment]
Closing due to the lack of response. Please reopen with more information if the problem still appears.
