### ISSUE TITLE
Race in `Thread.join()`

### ISSUE THREAD

**Issue by x42005e1f** [pypy/pypy#5079]
Hello, I was thinking and decided that I should let you know about a problem with the implementation of the [threading](https://docs.python.org/3/library/threading.html) module. As we all know, PyPy implements the [_thread](https://docs.python.org/3/library/_thread.html) module, but leaves the [threading](https://docs.python.org/3/library/threading.html) module as it is in CPython. As a consequence, PyPy suffers from [CPython's gh-116372](https://github.com/python/cpython/issues/116372). This leads to [RuntimeError](https://github.com/microsoft/vscode-python-debugger/issues/256), [AssertionError](https://github.com/pypy/pypy/issues/3474), and even [SEGFAULT](https://github.com/pypy/pypy/issues/2531).

In [my package](https://github.com/x42005e1f/aiologic), which is directly related to threading, I have implemented a [monkey patch](https://github.com/x42005e1f/aiologic/blob/760ab3dbe9cb59d1f3bb3dcd90b5a85b1f6f639c/src/aiologic/lowlevel/patcher.py#L403) that fixes this issue. You can also see a more detailed description of the problem in the function description. Hopefully, it will help you better understand the nature of the many related reports of threading issues that remain unresolved. Because, as I can see from [another issue](https://github.com/microsoft/debugpy/issues/1198), this problem is still shrouded in mystery.

**Comment by mattip** [comment]
Thanks. Would you like to submit a PR to target the py3.10 branch?

**Comment by mattip** [comment]
Maybe related to the timeouts on the [`test_del_shutdown (test.test_concurrent_futures.ThreadPoolShutdownTest)`](https://buildbot.pypy.org/summary/longrepr?testname=unmodified&builder=pypy-c-jit-linux-x86-64&build=11224&mod=lib-python.3.test.test_concurrent_futures) test on the buildbot

**Comment by mattip** [comment]
Thanks, committed in c9795377602
