### ISSUE TITLE
Latest night builds randomly fail with "undefined symbol: PyPy_FatalError"

### ISSUE THREAD

**Issue by skirpichev** [pypy/pypy#5086]
Build log: https://github.com/mpmath/mpmath/actions/runs/11405585574/job/31737386271?pr=879

First I've seen this yesterday.

**Comment by mattip** [comment]
Thanks for the report. Should be fixed by 392cf6462f, which is part of the newest nightly.

**Comment by skirpichev** [comment]
I confirm.
