### ISSUE TITLE
Implement or ignore faster startup via frozen modules

### ISSUE THREAD

**Issue by mattip** [pypy/pypy#5098]
One of the 3.11 speedups is for [faster startup](https://docs.python.org/3/whatsnew/3.11.html#faster-startup). This involves [freezing many stdlib modules](https://github.com/python/cpython/blame/556dc9b8a78bad296513221f3f414a3f8fd0ae70/Python/frozen.c#L75)
```
static const struct _frozen stdlib_modules[] = {
    /* stdlib - startup, without site (python -S) */
    {"abc", NULL, 0, false, GET_CODE(abc)},
    {"codecs", NULL, 0, false, GET_CODE(codecs)},
    {"io", NULL, 0, false, GET_CODE(io)},

    /* stdlib - startup, with site */
    {"_collections_abc", NULL, 0, false, GET_CODE(_collections_abc)},
    {"_sitebuiltins", NULL, 0, false, GET_CODE(_sitebuiltins)},
    {"genericpath", NULL, 0, false, GET_CODE(genericpath)},
    {"ntpath", NULL, 0, false, GET_CODE(ntpath)},
    {"posixpath", NULL, 0, false, GET_CODE(posixpath)},
    {"os.path", NULL, 0, false, GET_CODE(posixpath)},
    {"os", NULL, 0, false, GET_CODE(os)},
    {"site", NULL, 0, false, GET_CODE(site)},
    {"stat", NULL, 0, false, GET_CODE(stat)},

    /* runpy - run module with -m */
    {"importlib.util", NULL, 0, false, GET_CODE(importlib_util)},
    {"importlib.machinery", NULL, 0, false, GET_CODE(importlib_machinery)},
    {"runpy", NULL, 0, false, GET_CODE(runpy)},
    {0, 0, 0} /* stdlib sentinel */
};
static const struct _frozen test_modules[] = {
    {"__hello__", NULL, 0, false, GET_CODE(__hello__)},
    {"__hello_alias__", NULL, 0, false, GET_CODE(__hello__)},
    {"__phello_alias__", NULL, 0, true, GET_CODE(__hello__)},
    {"__phello_alias__.spam", NULL, 0, false, GET_CODE(__hello__)},
    {"__phello__", NULL, 0, true, GET_CODE(__phello__)},
    {"__phello__.__init__", NULL, 0, false, GET_CODE(__phello__)},
    {"__phello__.ham", NULL, 0, true, GET_CODE(__phello___ham)},
    {"__phello__.ham.__init__", NULL, 0, false, GET_CODE(__phello___ham)},
    {"__phello__.ham.eggs", NULL, 0, false, GET_CODE(__phello___ham_eggs)},
    {"__phello__.spam", NULL, 0, false, GET_CODE(__phello___spam)},
    {"__hello_only__", NULL, 0, false, GET_CODE(frozen_only)},
    {0, 0, 0} /* test sentinel */
};
```

This new features also comes with two flags to disable it: one if python is built with `Py_DEBUG` and another at runtime via `_imp._imp_override_frozen_modules_for_tests()`:

Currently, PyPy, like CPython 3.10 freezes only `_frozen_importlib`, `_frozen_importlib_external`, `zipimport`. The new flags do not override freezing these modules.

We could choose not to implement this optimization.

**Comment by cfbolz** [comment]
the way that we freeze so far is fundamentally different from how cpython does it. they 'only' freeze the code objects of the module, but still run the global code when the modules are imported. pypy otoh freezes all the interpreter-level object level instances *after* running the global code. that leads to much faster imports, but has the risk of hard-coding aspects of the build environment into the binary.

so if we want to go for more freezing we need to very carefully make sure that we aren't freezing e.g. paths.

**Comment by mattip** [comment]
Closing, this is not applicable to PyPy.
