### ISSUE TITLE
termios.tcget/setwinsize

### ISSUE THREAD

**Issue by cfbolz** [pypy/pypy#5108]
some new functions in the termios module: https://docs.python.org/3/library/termios.html#termios.tcgetwinsize

**Comment by mattip** [comment]
There is already [os.get_terminal_size](https://docs.python.org/3.11/library/os.html#os.get_terminal_size) and [shutil.get_terminal_size](https://docs.python.org/3.11/library/shutil.html#shutil.get_terminal_size). The [PR that added the new functions](https://github.com/python/cpython/pull/23686) did not relate to the other ones. I guess we can just repeat the get code in module/termios too. We will need to add the set code.

**Comment by mattip** [comment]
The CPython code supports first `winsize` but if that is not available falls back to `ttysize`. According to [this stackoverflow](https://stackoverflow.com/questions/18878141/difference-between-structures-ttysize-and-winsize) `ttysize` is obsolete.

**Comment by mattip** [comment]
Done in b9505e7442a.
