### ISSUE TITLE
`_curses.putp('')` without previous `initscr()` segfaults

### ISSUE THREAD

**Issue by devdanzin** [pypy/pypy#5116]
Calling `_curses.putp('')` without calling `_curses.initscr()` first segfaults. Doesn't happen in the REPL, probably because `initscr()` is called by it.

```python
import _curses
_curses.putp('')
```

PyPy version:
```
Python 3.10.14 (39dc8d3c85a7, Aug 27 2024, 14:32:27)
[PyPy 7.3.17 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
```

Found using fusil by @vstinner.

**Comment by mattip** [comment]
Thanks. Fixed in 6b367d9e671
