### ISSUE TITLE
implement a remote debugging mechanism

### ISSUE THREAD

**Issue by cfbolz** [pypy/pypy#5133]
I was talking with @pablogsal yesterday, and he described his idea for building a mechanism into a Python VM that would make it easier/possible to start a remote debugging session in an arbitrary Python process, using [`process_vm_writev`](https://linux.die.net/man/2/process_vm_writev).

I'll try to implement a prototype of this in PyPy, it's a very cool feature that I've wanted for ages.

**Comment by mattip** [comment]
There was once upon a time [pyrasite](https://github.com/lmacken/pyrasite) for code injection and [bytehook](https://github.com/tzickel/bytehook) for adding a function hook. This could be combined with something like [rdb](https://py-toolbox.readthedocs.io/en/latest/modules/rdb.html#remote-debugging) which allows debugging over a socket.

**Comment by cfbolz** [comment]
Oh, pyrasite is neat, I wasn't aware, thanks for the pointer! Yeah, it would be a lot like that, just implemented differently.

**Comment by mattip** [comment]
Closing since the feature was implemented, please reopen or open a new issue if there is more to do here
