### ISSUE TITLE
Incorrect readonly field in Py_buffer

### ISSUE THREAD

**Issue by cclin0816** [pypy/pypy#5136]
When passing buffer to C extension, the readonly field might be set while it shouldn't

C extension:
```c
#define PY_SSIZE_T_CLEAN
#include <Python.h>

static PyObject *method(PyObject *self, PyObject *args) {
  Py_buffer buf;
  if (!PyArg_ParseTuple(args, "y*", &buf))
    return NULL;
  int ro = buf.readonly;
  PyBuffer_Release(&buf);

  return ro ? Py_True : Py_False;
}

static struct PyMethodDef methods[] = {
    {"method", method, METH_VARARGS, NULL},
    {NULL, NULL, 0, NULL},
};

static struct PyModuleDef mod = {
    PyModuleDef_HEAD_INIT, "c_mod", NULL, 0, methods, NULL, NULL, NULL, NULL,
};

PyMODINIT_FUNC PyInit_mod() { return PyModule_Create(&mod); }
```

python test:
```python
from ctypes import c_uint8
import mod
import numpy
import array

# only happens sometimes, so spin for a while
for _ in range(10000):
    # all four type failed
    # buf = array.array("B", [0] * 1024)
    # buf = bytearray(1024)
    # buf = numpy.zeros((1024), dtype=numpy.uint8).tobytes()
    buf = (c_uint8 * 1024)()
    if mod.method(buf):
        raise ValueError(f"buffer readonly {type(buf)}")
```

system setup
  * python: pypy3.10-v7.3.17 (tested on pypy3.6-v7.3.1 and still remains)
  * os: EndeavourOS x86_64

  
Probably the same bug as #4918, #4992

**Comment by mattip** [comment]
Just to be clear: does the problem happen when using the other alternative ways of creating `buf`, or only with ctypes?

**Comment by mattip** [comment]
Also: if you track the index of the failure, does it always fail on the same iteration?

**Comment by cclin0816** [comment]
all four type will fail, not just ctypes
surprisingly first two are fairly consistent, 1 and 1071 (0 base) on my platform,
after that isn't  that deterministic, but seems to be contiguous block,

**Comment by mattip** [comment]
The field was uninitialized, so sometimes it got the correct value by mistake. Fixed in 1bf2407648a3

**Comment by mattip** [comment]
@cclin0816 could you check again with a nightly build of py3.10 or py3.11?

**Comment by mattip** [comment]
Closing as fixed, please reopen or open a new issue if I missed something.
