### ISSUE TITLE
Non-Unicode Path Decoding Error with PyPy

### ISSUE THREAD

**Issue by wojiaoyishang** [pypy/pypy#5138]
![image](https://github.com/user-attachments/assets/1cee46e5-da91-4b0f-b13e-91e2fb7a5f75)
Description: I encountered a UnicodeDecodeError when attempting to run a Python script using PyPy. The error seems to occur during the decoding of a non-Unicode byte sequence. Specifically, I received the following error message:

C:\Users\lovep\AppData\Local\Programs\Python\pypy3.10\pypy.exe: can't open file E:\\udca4\udcb9\udca4\udcc1\udca4栅\udcb9\udca4\udcaf.py: [Errno 2] No such file or directory

Steps to Reproduce:

Use PyPy to run a Python script that reads a file or input containing non-UTF-8 path sequences.
The script should throw a Error during decoding.

This issue does not occur when running the script using the standard CPython interpreter, which seems to handle paths with non-ASCII characters without issue. But it works fine on Linux x86 64-bit.

Environment:
PyPy version: PyPy 7.3.17
OS: Windows
Python version: 3.10.14 (PyPy 7.3.17)

**Comment by wojiaoyishang** [comment]
![image](https://github.com/user-attachments/assets/c4d9bcf3-614f-40a0-ae04-b3f90e86ef52)

By the way, pip's progress display maybe strange

**Comment by mattip** [comment]
> By the way, pip's progress display maybe strange

That is #3776

**Comment by mattip** [comment]
Took a bit of look at this. I think what we need is to use `wchar_t` `argv` handling in `main`, which is defined here https://github.com/pypy/pypy/blob/ee129c65e3f894691cd58ff313439fb518a8cf7e/rpython/translator/platform/windows.py#L507-L510

Windows supports spelling this as
```diff
-                   'echo '
-                   'int $(PYPY_MAIN_FUNCTION)(int, char*[]); '
-                   'int main(int argc, char* argv[]) '
-                   '{ return $(PYPY_MAIN_FUNCTION)(argc, argv); } > $@')
+                   ['echo #define WIN32_LEAN_AND_MEAN > $@.tmp',
+                    'echo #include "stdlib.h" >> $@.tmp',
+                    'echo #include "windows.h" >> $@.tmp',
+                    'echo int $(PYPY_MAIN_FUNCTION)(int, wchar_t*[]); >> $@.tmp',
+                   'echo int wmain(int argc, wchar_t* argv[]) { >> $@.tmp',
+                   'echo   return $(PYPY_MAIN_FUNCTION)(argc, argv); } >> $@.tmp',
+                    'move $@.tmp $@',
```

Then we would have to percolate that into `PYPY_MAIN_FUNCTION` and `pypy_main_function`, which are in `rpython/translator/c/src/entrypoint.c`, through [`entrypoint_wrapper`](https://github.com/pypy/pypy/blob/ee129c65e3f894691cd58ff313439fb518a8cf7e/rpython/translator/c/genc.py#L261), and into [`app_main`](https://github.com/pypy/pypy/blob/ee129c65e3f894691cd58ff313439fb518a8cf7e/pypy/interpreter/app_main.py#L875). The tricky bits are separating the windows argv-as-unicode-wchar from the linux argv-as-surrogate-encoded-bytes and testing.
