### ISSUE TITLE
Fully manual garbage collection?

### ISSUE THREAD

**Issue by leo-ard** [pypy/pypy#5150]
Hi! 

I'm working on a gc prototype and would like to know if there is a way to manually manage memory in PyPy. From the doc, I can see a `gc.disable()` option allowing me to disable the gc. However, I don't see any function for manually collect a certain object, something like `gc.free(obj)`. I know this can lead to memory corruption or invalid references; and this is probably why this "feature" is not implemented. But I'm wondering if there is a "hacky" way to do something like this?

Thanks in advance!

**Comment by cfbolz** [comment]
sorry, there's absolutely no chance that this can be achieved, even in a hacky way. One immediate problem is that the VM has a lot of internal objects that aren't even accessible as python objects.

**Comment by leo-ard** [comment]
Oh I see, it's true that Pypy manages objects that are internal to the VM, so a 'real' garbage collector couldn't be possible. However, I'm wondering if it could be possible to still manage python objects that are explicitly created? Thinking more about it, the primitives I'm looking for are more a-kind to the malloc/free primitives of C, but for python objects. Would something like this be possible/hackable ?

**Comment by mattip** [comment]
Micro managing object creation and destruction is not possible. Closing.
