### ISSUE TITLE
ctypes.ARRAY in PyPy does not raise IndexError for out-of-bounds access

### ISSUE THREAD

**Issue by mouchen626** [pypy/pypy#5152]
While using ctypes.ARRAY in PyPy, I noticed that attempting to access an out-of-bounds index does not raise an IndexError, which is the behavior I expected based on CPython. Instead, it silently returns an empty or default value. I'm not sure if this is intentional or if it's a potential oversight in the ctypes implementation in PyPy.

```python
import ctypes

IntArray5 = ctypes.ARRAY(ctypes.c_int, 5)

arr = IntArray5(1, 2, 3, 4, 5)
print(arr[6])  # Attempt to access out-of-bounds index
```

Expected Behavior:
Based on how ctypes.ARRAY behaves in CPython, I expected an IndexError to be raised when accessing an out-of-bounds index.

Actual Behavior:
The code runs without any exception and outputs an empty value instead.

**Comment by mattip** [comment]
What version of PyPy on what platform? This raises an IndexError for me on `pypy3.10-v7.3.16-linux64`

**Comment by mattip** [comment]
@mouchen626 can you update this issue or should we close it?
