### ISSUE TITLE
read_setup_file, parse_makefile not there in distutils

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#535]
In Heptapod by bitbucket_importer on May 16, 2010, 14:23

*Created originally on Bitbucket by [illume (René Dudfield)](https://bitbucket.org/[7.3.7](https://github.com/gitlab-importer/pypy/milestone/7)B439dcffd-3404-48a2-bf24-bb80a3a38b8b%7D/)*

**From (bugs.pypy.org)**

**Comment by devdanzin** [comment]
This can be closed, importing `read_setup_file` works on PyPy 7.3.16 for Python 3.10.14.

```python
from distutils.sysconfig import parse_makefile
from distutils.extension import read_setup_file
```

**Comment by mattip** [comment]
Thanks, closing.
