### ISSUE TITLE
CTRL-leftarrow and CTRL-rightarrow don't work in PyPy console

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#906]
In Heptapod by bitbucket_importer on Oct 12, 2011, 13:23

*Created originally on Bitbucket by [vak](https://bitbucket.org/[7.3.7](https://github.com/gitlab-importer/pypy/milestone/7)B665e32bf-c935-4c9e-a666-60ddc3f67bb0%7D/)*

**From (bugs.pypy.org)**

**Comment by cfbolz** [comment]
I've backported this as a separate issue from #4990 because I wanted the fix in pypy2 as well (has been annoying me since forever).
